/* ─────────────────────────────────────────────────────────────────
   JEO-SCRABBLE — KELIME BANKASI
   Format: { en, tr, unit, grade }
   unit  : hangi üniteye ait olduğunu belirtir (1-10, 11=Irregular Verbs)
   grade : hangi sınıf seviyesine ait olduğunu belirtir (names.js'teki grade ile eşleşir)
           Tek sınıf: grade: 7
           Birden fazla sınıf: grade: [6,7,8]
   Settings'ten seçilen sınıf + üniteler yarışmaya dahil edilir.
───────────────────────────────────────────────────────────────── */
const WORD_BANK = {
  easy: [
    { en: 'ACCEPT', tr: 'KABUL ETMEK',  unit: [1,7] , grade: [7] },
    { en: 'DRANK',  tr: 'DRINK',  unit: 11, grade: [6,7] },
    { en: 'GOT',    tr: 'GET',    unit: 11, grade: [6,7] },
    { en: 'SWAM',   tr: 'SWIM',   unit: 11, grade: [6,7] },
    { en: 'READ',   tr: 'READ',   unit: 11, grade: [6,7] },
    { en: 'MADE',   tr: 'MAKE',   unit: 11, grade: [6,7] },
    { en: 'WENT',   tr: 'GO',     unit: 11, grade: [6,7] },
    { en: 'COOL',   tr: 'HAVALI',   unit: 1, grade: 8 },
    { en: 'SHARE',   tr: 'PAYLAŞMAK',   unit: 1, grade: 8 },
    { en: 'BEST',   tr: '.... FRIEND - EN İYİ ARKADAŞ',   unit: 1, grade: 8 },
    { en: 'INVITE',   tr: 'DAVET ETMEK',   unit: 1, grade: 8 },
    { en: 'FRIENDSHIP',   tr: 'ARKADAŞLIK',   unit: 1, grade: 8 },
    { en: 'SHY',      tr: 'UTANGAÇ',          unit: 1, grade: 7 },
    { en: 'TALL',     tr: 'UZUN BOYLU',       unit: 1, grade: 7 },
    { en: 'SLIM',     tr: 'ZAYIF',            unit: 1, grade: 7 },
    { en: 'SELFISH',  tr: 'BENCİL',           unit: 1, grade: 7 },
    { en: 'FRIENDLY', tr: 'ARKADAŞ CANLISI',  unit: 1, grade: 7 },
    { en: 'SOCIABLE', tr: 'SOSYAL',           unit: 1, grade: 7 },
    { en: 'BLONDE',    tr: 'SARIŞIN (SAÇ)',    unit: 1, grade: 7 },
    { en: 'YOUNG',     tr: 'GENÇ',            unit: 1, grade: 7 },
    { en: 'FAT',       tr: 'ŞİŞMAN',          unit: 1, grade: 7 },
    { en: 'UGLY',      tr: 'ÇİRKİN',          unit: 1, grade: 7 },
    { en: 'QUIET',     tr: 'SESSİZ',          unit: 1, grade: 7 },
    { en: 'ENERGETIC', tr: 'ENERJİK',         unit: 1, grade: 7 },
    { en: 'HANDSOME',  tr: 'YAKIŞIKLI',       unit: 1, grade: 7 },
    { en: 'HONEST',   tr: 'DÜRÜST',           unit: 1, grade: [7,8] },
    { en: 'TOGETHER',   tr: 'BERABER',   unit: 1, grade: 8 },
    { en: 'BEAUTIFUL',   tr: 'GÜZEL (PRETTY)',  unit: 1, grade: 7 },
    { en: 'WEEKEND',      tr: 'HAFTA SONU',             unit: 1, grade: 6 },
    { en: 'WEEKDAYS',     tr: 'HAFTAİÇİ',               unit: 1, grade: 6 },
    { en: 'SHOPPING',  tr: 'GO ........ ALIŞVERİŞE ÇIKMAK',      unit: 1, grade: 6 },
    { en: 'ONLINE',    tr: 'GO ...... İNTERNETE GİRMEK',       unit: 1, grade: 6 },
    { en: 'HOMEWORK',  tr: 'DO ........ EV ÖDEVİ YAPMAK',        unit: 1, grade: 6 },
    { en: 'FRIENDS', tr: 'MEET ....... ARKADAŞLARLA BULUŞMAK',  unit: 1, grade: 6 },
    { en: 'REST',  tr: 'HAVE A .... DİNLENMEK',              unit: 1, grade: 6 },
    { en: 'SNACK', tr: 'HAVE A ..... ATIŞTIRMAK',             unit: 1, grade: 6 },
    { en: 'FOLK',      tr: '.... DANCE - HALK OYUNLARI',          unit: 1, grade: 6 },
  ],
  medium: [
    { en: 'HAD',    tr: 'HAVE',   unit: 11, grade: 6 },
    { en: 'LOST',   tr: 'LOSE',   unit: 11, grade: 6 },
    { en: 'DID',    tr: 'DO',     unit: 11, grade: 6 },
    { en: 'TOOK',   tr: 'TAKE',   unit: 11, grade: 6 },
    { en: 'BOUGHT', tr: 'BUY',    unit: 11, grade: 6 },
    { en: 'SAW',    tr: 'SEE',    unit: 11, grade: 6 },
    { en: 'ATE',    tr: 'EAT',    unit: 11, grade: 6 },
    { en: 'WROTE',  tr: 'WRITE',  unit: 11, grade: 6 },
    { en: 'RODE',   tr: 'RIDE',   unit: 11, grade: 6 },

    { en: 'SUPPORT',   tr: 'BACK UP Eşanlamlısı',   unit: 1, grade: 8 },
    { en: 'MATE',   tr: 'BUDDY Eşanlamlısı',   unit: 1, grade: 8 },
    { en: 'TRUST',   tr: 'RELY ON Eşanlamlısı',   unit: 1, grade: 8 },
    { en: 'SECRET',   tr: 'KEEP ... - SIR TUTMAK',   unit: 1, grade: 8 },
    { en: 'CLOSE',   tr: '.... FRIEND - YAKIN ARKADAŞ',   unit: 1, grade: 8 },
    { en: 'ACCEPT',   tr: 'KABUL ETMEK',   unit: 1, grade: 8 },
    { en: 'REFUSE',   tr: 'REDDETMEK',   unit: 1, grade: 8 },
    { en: 'TRUTH',   tr: 'TELL .... - DOĞRUYU SÖYLEMEK',   unit: 1, grade: 8 },
    { en: 'LIES',   tr: 'TELL .... - YALAN SÖYLEMEK',   unit: 1, grade: 8 },
    { en: 'ATTEND',   tr: 'JOIN Eşanlamlısı',   unit: 1, grade: 8 },
    { en: 'SENDER',   tr: 'GÖNDERİCİ',   unit: 1, grade: 8 },
    { en: 'GENEROUS',   tr: 'CÖMERT',   unit: 1, grade: [7,8] },
    { en: 'STINGY',   tr: 'CİMRİ ',   unit: 1, grade: [7,8] },
    { en: 'POLITE',   tr: 'KIND Eşanlamlısı',   unit: 1, grade: 8 },
    { en: 'SLUMBER',   tr: 'SLEEPOVER Eşanlamlısı',   unit: 1, grade: 8 },
    { en: 'ARGUE',   tr: 'TARTIŞMAK-KAVGA ETMEK',   unit: 1, grade: 8 },
    { en: 'UNTIL',   tr: 'KADAR',   unit: 1, grade: 8 },

    { en: 'BALD',        tr: 'KEL',            unit: 1, grade: 7 },
    { en: 'CURLY',       tr: 'KIVIRCIK',       unit: 1, grade: 7 },
    { en: 'WAVY',        tr: 'DALGALI',        unit: 1, grade: 7 },
    { en: 'HAZEL',       tr: 'ELA',            unit: 1, grade: 7 },
    { en: 'OUTGOING',    tr: 'CANA YAKIN',     unit: 1, grade: 7 },
    { en: 'EASYGOING',   tr: 'UYUMLU',         unit: 1, grade: 7 },
    { en: 'OVERWEIGHT',  tr: 'AŞIRI KİLOLU',   unit: 1, grade: 7 },
    { en: 'POLITE',      tr: 'KİBAR',          unit: 1, grade: [7,8] },
    { en: 'BEARD',       tr: 'SAKAL',           unit: 1, grade: 7 },
    { en: 'GLASSES',     tr: 'GÖZLÜK',          unit: 1, grade: 7 },
    { en: 'SCAR',        tr: 'YARA İZİ',        unit: 1, grade: 7 },

    { en: 'ONCE',           tr: 'BİR KEZ',                unit: 1, grade: 6 },
    { en: 'TWICE',          tr: 'İKİ KEZ',                unit: 1, grade: 6 },
    { en: 'AFTER',          tr: 'SONRA',                  unit: 1, grade: 6 },
    { en: 'ALWAYS',         tr: 'HER ZAMAN',              unit: 1, grade: 6 },
    { en: 'NEVER',          tr: 'ASLA - HİÇ',             unit: 1, grade: 6 },
    { en: 'OFTEN',          tr: 'SIK SIK',                unit: 1, grade: 6 },
    { en: 'SOMETIMES',      tr: 'BAZEN',                  unit: 1, grade: 6 },
    { en: 'HOWOFTEN',      tr: 'NE SIKLIKLA',            unit: 1, grade: 6 },
    { en: 'HANGOUT',       tr: 'TAKILMAK',               unit: 1, grade: 6 },

  ],
  hard: [
    { en: 'CAME',    tr: 'COME',   unit: 11, grade: 6 },
    { en: 'TOLD',    tr: 'TELL',   unit: 11, grade: 6 },
    { en: 'SOLD',    tr: 'SELL',   unit: 11, grade: 6 },
    { en: 'DREW',    tr: 'DRAW',   unit: 11, grade: 6 },
    { en: 'SAID',    tr: 'SAY',    unit: 11, grade: 6 },
    { en: 'SPOKE',   tr: 'SPEAK',  unit: 11, grade: 6 },
    { en: 'WOKE',    tr: 'WAKE',   unit: 11, grade: 6 },
    { en: 'FELT',    tr: 'FEEL',   unit: 11, grade: 6 },
    { en: 'SAT',     tr: 'SIT',    unit: 11, grade: 6 },
    { en: 'BROUGHT', tr: 'BRING',  unit: 11, grade: 6 },
    { en: 'WON',     tr: 'WIN',    unit: 11, grade: 6 },
    { en: 'FLEW',    tr: 'FLY',    unit: 11, grade: 6 },
    { en: 'GAVE',    tr: 'GIVE',   unit: 11, grade: 6 },
    { en: 'BROKE',   tr: 'BREAK',  unit: 11, grade: 6 },
    { en: 'CAUGHT',  tr: 'CATCH',  unit: 11, grade: 6 },
    { en: 'FED',     tr: 'FEED',   unit: 11, grade: 6 },
    { en: 'LEFT',    tr: 'LEAVE',  unit: 11, grade: 6 },
    { en: 'DROVE',   tr: 'DRIVE',  unit: 11, grade: 6 },
    { en: 'RAN',     tr: 'RUN',    unit: 11, grade: 6 },
    { en: 'FELL',    tr: 'FALL',   unit: 11, grade: 6 },
    { en: 'SLEPT',   tr: 'SLEEP',  unit: 11, grade: 6 },

    { en: 'COUNTON',   tr: 'DEPEND ON Eşanlamlısı',   unit: 1, grade: 8 },
    { en: 'EXCUSE',   tr: 'MAKE AN ..... - MAZERET BİLDİRMEK',   unit: 1, grade: 8 },
    { en: 'APOLOGIZE',   tr: 'ÖZÜR DİLEMEK',   unit: 1, grade: 8 },
    { en: 'DEADLINE',   tr: 'SON BAŞVURU TARİHİ',   unit: 1, grade: 8 },
    { en: 'RECEIVER',   tr: 'ALICI',   unit: 1, grade: 8 },
    { en: 'RESPONSE',   tr: 'YANIT',   unit: 1, grade: 8 },
    { en: 'JEALOUS',   tr: 'KISKANÇ',   unit: 1, grade: 8 },
    { en: 'SIMILAR',   tr: 'HAVE ... INTERESTS -BENZER İLGİ ALANLARI',   unit: 1, grade: 8 },
    { en: 'COMMON',   tr: 'HAVE SOMETHING IN .... - ORTAK BİRŞEYLERİN OLMASI',   unit: 1, grade: 8 },
    { en: 'RELATIONSHIP',   tr: 'İLİŞKİ',   unit: 1, grade: 8 },
    { en: 'STUBBORN',   tr: 'İNATÇI',   unit: 1, grade: [7,8] },
    { en: 'INFORM',   tr: 'BİLGİLENDİRMEK',   unit: 1, grade: 8 },
    { en: 'DETERMINED',   tr: 'KARARLI',   unit: 1, grade: 8 },
    { en: 'TACTFUL',   tr: 'DÜŞÜNCELİ',   unit: 1, grade: 8 },
    { en: 'RELIABLE',   tr: 'GÜVENİLİR',   unit: 1, grade: [7,8] },
    { en: 'DECIDE',   tr: 'KARAR VERMEK',   unit: 1, grade: 8 },
    { en: 'CELEBRATE',   tr: 'KUTLAMAK',   unit: 1, grade: 8 },

    { en: 'PLUMP',         tr: 'TOMBUL',         unit: 1, grade: 7 },
    { en: 'CLUMSY',        tr: 'SAKAR',          unit: 1, grade: 7 },
    { en: 'PUNCTUAL',      tr: 'DAKİK',          unit: 1, grade: 7 },
    { en: 'TALENTED',      tr: 'YETENEKLİ',      unit: 1, grade: 7 },
    { en: 'FORGETFUL',     tr: 'UNUTKAN',        unit: 1, grade: 7 },
    { en: 'THOUGHTFUL',    tr: 'DÜŞÜNCELİ',      unit: 1, grade: 7 },
    { en: 'APPEARANCE',    tr: 'GÖRÜNÜŞ',        unit: 1, grade: 7 },
    { en: 'ATTRACTIVE',    tr: 'ÇEKİCİ',         unit: 1, grade: 7 },
    { en: 'MEDIUM-HEIGHT', tr: 'ORTA BOYLU',     unit: 1, grade: 7 },
    { en: 'STUMPY',        tr: 'BODUR',          unit: 1, grade: 7 },
    { en: 'GET ON WELL',   tr: 'İYİ GEÇİNMEK',  unit: 1, grade: 7 },
    { en: 'PERSONALITY',   tr: 'KİŞİLİK',        unit: 1, grade: 7 },
    { en: 'INTELLIGENT',   tr: 'ZEKİ (CLEVER)',  unit: 1, grade: 7 },
    { en: 'MIDDLE-AGED',   tr: 'ORTA YAŞLI',    unit: 1, grade: 7 },
    { en: 'HEADSCARF',     tr: 'BAŞ ÖRTÜSÜ',    unit: 1, grade: 7 },
    { en: 'CHANGE MIND',   tr: 'FİKİR DEĞİŞTİRMEK', unit: 1, grade: 7 },
    { en: 'CHEERFUL',    tr: 'NEŞELİ',         unit: 1, grade: 7 },
    { en: 'STRAIGHT',    tr: 'DÜZ SAÇ',         unit: 1, grade: 7 },
    { en: 'STRICT',      tr: 'SERT',            unit: 1, grade: 7 },
    { en: 'SERIOUS',     tr: 'CİDDİ',           unit: 1, grade: 7 },
    { en: 'MOUSTACHE',   tr: 'BIYIK',           unit: 1, grade: 7 },

    { en: 'SELDOM',          tr: 'RARELY Eşanlamlısı',       unit: 1, grade: 6 },
    { en: 'DIARY',           tr: 'GÜNLÜK',                 unit: 1, grade: 6 },
    { en: 'RELATIVES', tr: 'VISIT ......... AKRABALARI ZİYARET',     unit: 1, grade: 6 },
    { en: 'ERRANDS',     tr: 'RUN ....... AYAK İŞLERİ YAPMAK',    unit: 1, grade: 6 },
    { en: 'ENROLL',          tr: 'BAŞVURMAK',              unit: 1, grade: 6 },
    { en: 'MEMBERSHIP',      tr: 'ÜYELİK',                unit: 1, grade: 6 },
    { en: 'NEIGHBORHOOD',    tr: 'MAHALLE - ÇEVRE',        unit: 1, grade: 6 },
    { en: 'TRADITIONAL',     tr: 'GELENEKSEL',             unit: 1, grade: 6 },
    { en: 'USUALLY',        tr: 'GENELLİKLE',             unit: 1, grade: 6 },

  ]
};

const DIFF_SCORES = { easy: 10, medium: 20, hard: 30 };
const DIFF_LABELS = { easy: 'EASY', medium: 'MEDIUM', hard: 'HARD' };

/* ─────────────────────────────────────────────────────────────────
   TUTORIAL KELİMELERİ — unit: 0
   Oyun mekaniğini öğretmek için kullanılır.
   Çok basit, kısa, yaygın İngilizce kelimeler.
   Puan/zorluk/süre sistemi YOKTUR.
─────────────────────────────────────────────────────────────────── */
const TUTORIAL_WORDS = [
  { en: 'CAT',    tr: 'KEDI'        },
  { en: 'DOG',    tr: 'KÖPEK'       },
  { en: 'SUN',    tr: 'GÜNEŞ'       },
  { en: 'BIG',    tr: 'BÜYÜK'       },
  { en: 'RED',    tr: 'KIRMIZI'     },
  { en: 'GOOD',   tr: 'İYİ'         },
  { en: 'FISH',   tr: 'BALIK'       },
  { en: 'BIRD',   tr: 'KUŞ'         },
  { en: 'BOOK',   tr: 'KİTAP'       },
  { en: 'BLUE',   tr: 'MAVİ'        },
  { en: 'FAST',   tr: 'HIZLI'       },
  { en: 'PLAY',   tr: 'OYNAMAK'     },
  { en: 'HAPPY',  tr: 'MUTLU'       },
  { en: 'LONG',   tr: 'UZUN'        },
  { en: 'APPLE',  tr: 'ELMA'        },
  { en: 'GREEN',  tr: 'YEŞİL'       },
  { en: 'WATER',  tr: 'SU'          },
  { en: 'LEARN',  tr: 'ÖĞRENMEK'    },
  { en: 'HOUSE',  tr: 'EV'          },
  { en: 'DANCE',  tr: 'DANS ETMEK'  },
];
