// ============================================================
// ENEMIES.JS — Word Rivals Solo: Enemy Definitions
//
// Her düşman için:
//   id         : benzersiz kimlik
//   name       : gösterilecek isim (büyük harf)
//   level      : seviye (NPC panel'de görünür)
//   maxHp      : maksimum can puanı
//   att        : saldırı gücü — yanlış cevap / süre dolunca oyuncuya bu kadar HP vurur
//   xpReward   : yenilince kazanılan XP
//   goldReward : sandıktan çıkacak altın aralığı [minimum, maksimum]
//   emoji      : görsel yoksa placeholder emoji
//   color      : tema rengi (HP bar, isim rengi, vb.)
//   img        : görsel yolu — null = emoji placeholder kullan
//   facesRight : true → görsel sağa bakıyor
//   flying     : 1 → uçuyor (yukarı-aşağı + yatay hareket), 0 → yerde (sadece yatay)
//   vertical   : 1 → dikey/humanoid yerleşim (2:3), 0 → yatay/beast yerleşim (3:2)
//   oversized  : 1 → normalden büyük/dev görünüm, 0 veya yok → normal boyut
//   unitSet    : soru gelecek ünite numaraları — null → tüm üniteler
// ============================================================

const ENEMIES = [
  {
    order: 1,
    id: 'rat',
    name: 'RAT',
    level: 1,
    maxHp: 20,
    att: 5,
    xpReward: 20,
    goldReward: [5, 10],
    emoji: '🐀',
    color: '#4ade80',
    img: 'enemies/rat.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [1],
  },
  {
    order: 2,
    id: 'boar',
    name: 'BOAR',
    level: 1,
    maxHp: 30,
    att: 7,
    xpReward: 25,
    goldReward: [5, 10],
    emoji: '🐗',
    color: '#4ade80',
    img: 'enemies/boar.webp',
    facesRight: false,
    flying: 0,
    vertical: 0,
    unitSet: [1],
  },
  {
    order: 3,
    id: 'kobold',
    name: 'KOBOLD',
    level: 2,
    maxHp: 35,
    att: 9,
    xpReward: 25,
    goldReward: [5, 10],
    emoji: '🦇',
    color: '#4ade80',
    img: 'enemies/kobold.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    unitSet: [1, 2],
  },
  {
    order: 4,
    id: 'goblin',
    name: 'GOBLIN',
    level: 2,
    maxHp: 40,
    att: 10,
    xpReward: 30,
    goldReward: [10, 20],
    emoji: '👺',
    color: '#4ade80',
    img: 'enemies/goblin.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    unitSet: [1, 2],
  },
  {
    order: 5,
    id: 'scarecrow',
    name: 'SCARECROW',
    level: 3,
    maxHp: 50,
    att: 11,
    xpReward: 35,
    goldReward: [15, 30],
    emoji: '👿',
    color: '#f97316',
    img: 'enemies/scarecrow.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    unitSet: [2, 3],
  },
  {
    order: 6,
    id: 'wolf',
    name: 'WOLF',
    level: 3,
    maxHp: 55,
    att: 12,
    xpReward: 40,
    goldReward: [15, 30],
    emoji: '👾',
    color: '#a855f7',
    img: 'enemies/wolf.webp',
    facesRight: false,
    flying: 0,
    vertical: 0,
    unitSet: [2, 3],
  },
  {
    order: 7,
    id: 'harpy',
    name: 'HARPY',
    level: 4,
    maxHp: 60,
    att: 15,
    xpReward: 45,
    goldReward: [20, 40],
    emoji: '🧌',
    color: '#ef4444',
    img: 'enemies/harpy.webp',
    facesRight: false,
    flying: 1,
    vertical: 1,
    unitSet: [3, 4],
  },
  {
    order: 8,
    id: 'centaur',
    name: 'CENTAUR',
    level: 4,
    maxHp: 65,
    att: 18,
    xpReward: 50,
    goldReward: [25, 50],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/centaur.webp',
    facesRight: false,
    flying: 0,
    vertical: 0,
    unitSet: [2, 3, 4],
  },

{
    order: 9,
    id: 'bandit',
    name: 'BANDIT HENCHMAN',
    level: 5,
    maxHp: 70,
    att: 20,
    xpReward: 75,
    goldReward: [30, 60],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/bandit.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    unitSet: [3, 4, 5],
  },
{
    order: 10,
    id: 'banditboss',
    name: 'BANDIT LEADER',
    level: 8,
    maxHp: 80,
    att: 25,
    xpReward: 100,
    goldReward: [25, 50],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/banditboss.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5],
},

{
    order: 11,
    id: 'spider',
    name: 'SPIDER',
    level: 5,
    maxHp: 70,
    att: 20,
    xpReward: 75,
    goldReward: [30, 60],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/spider.webp',
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [6],
},
{
    order: 12,
    id: 'bogwitch',
    name: 'BOG WITCH',
    level: 6,
    maxHp: 75,
    att: 25,
    xpReward: 75,
    goldReward: [35, 70],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/bogwitch.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [6],


  },

{
    order: 13,
    id: 'myconid',
    name: 'MYCONID',
    level: 6,
    maxHp: 80,
    att: 25,
    xpReward: 80,
    goldReward: [40, 80],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/myconid.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [6, 7],


  },
{
    order: 14,
    id: 'dryad',
    name: 'DRYAD',
    level: 7,
    maxHp: 85,
    att: 30,
    xpReward: 85,
    goldReward: [45, 90],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/dryad.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [6, 7],


  },

{
    order: 15,
    id: 'lizardman',
    name: 'LIZARDMAN',
    level: 7,
    maxHp: 90,
    att: 35,
    xpReward: 90,
    goldReward: [50, 100],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/lizardman.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [8],


  },

{
    order: 16,
    id: 'werewolf',
    name: 'WEREWOLF',
    level: 8,
    maxHp: 95,
    att: 35,
    xpReward: 95,
    goldReward: [55, 110],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/werewolf.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [8, 9],


  },

{
    order: 17,
    id: 'basilisk',
    name: 'BASILISK',
    level: 8,
    maxHp: 100,
    att: 40,
    xpReward: 100,
    goldReward: [60, 120],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/basilisk.webp',
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [9],


  },
{
    order: 18,
    id: 'troll',
    name: 'TROLL',
    level: 9,
    maxHp: 110,
    att: 45,
    xpReward: 105,
    goldReward: [65, 130],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/troll.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [9, 10],


  },

{
    order: 19,
    id: 'wendigo',
    name: 'WENDIGO',
    level: 9,
    maxHp: 115,
    att: 50,
    xpReward: 110,
    goldReward: [70, 140],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/wendigo.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [8, 9, 10],


  },
{
    order: 20,
    id: 'ancienttreant',
    name: 'ANCIENT TREANT',
    level: 12,
    maxHp: 150,
    att: 70,
    xpReward: 150,
    goldReward: [100, 150],
    emoji: '☠️',
    color: '#FFD700',
    img: 'enemies/treant.webp',
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],


  },
];
