// ============================================================
// ENEMIES.JS — Word Rivals Solo: Enemy Definitions
//
// Her düşman için:
//   id         : benzersiz kimlik
//   name       : gösterilecek isim (büyük harf)
//   level      : seviye (NPC panel'de görünür)
//   maxHp      : maksimum can puanı
//   att        : saldırı gücü — yanlış cevap / süre dolunca oyuncuya bu kadar HP vurur
//   speed      : düşmanın saldırması için gereken saniye (düşük değer = daha hızlı)
//   xpReward   : yenilince kazanılan XP
//   goldReward : sandıktan çıkacak altın aralığı [minimum, maksimum]
//   emoji      : görsel yoksa placeholder emoji
//   color      : tema rengi (HP bar, isim rengi, vb.)
//   img        : görsel yolu — null = emoji placeholder kullan
//   facesRight : true → görsel sağa bakıyor
//   flying     : 1 → uçuyor (yukarı-aşağı + yatay hareket), 0 → yerde (sadece yatay)
//   vertical   : 1 → dikey/humanoid yerleşim (2:3), 0 → yatay/beast yerleşim (3:2)
//   oversized  : 1 → normalden büyük/dev görünüm, 0 veya yok → normal boyut
//   unitSet    : soru gelecek ünite numaraları — null → tüm üniteler
// ============================================================

// Enemy rarity stat sets are stored here so balancing stays in enemies.js.
// Boss encounters (every 5th enemy) roll Rare or better in the game logic.
// Minimum player POWER required before Common/Uncommon enemies in each biome
// can appear as duos: Plains, Forest, Frost, Lava, Celestial.
const DUO_POWER_THRESHOLDS = [100, 180, 280, 400, 550];

function enemyRarityVersions(hp, att, speed, xpReward, goldReward) {
  const gold = Array.isArray(goldReward) ? goldReward : [goldReward, goldReward];
  const scaleRange = mult => gold.map(value => Math.max(1, Math.round(value * mult)));
  return {
    common:    { hp,                      att,                      speed,                  xpReward,                      goldReward: gold },
    uncommon:  { hp: Math.round(hp*1.3), att: Math.round(att*1.2), speed,                  xpReward: Math.round(xpReward*1.3), goldReward: scaleRange(1.3) },
    rare:      { hp: Math.round(hp*1.7), att: Math.round(att*1.5), speed,                  xpReward: Math.round(xpReward*1.7), goldReward: scaleRange(1.7) },
    epic:      { hp: Math.round(hp*2.3), att: Math.round(att*1.9), speed,                  xpReward: Math.round(xpReward*2.3), goldReward: scaleRange(2.3) },
    legendary: { hp: Math.round(hp*3.5), att: Math.round(att*2.5), speed,                  xpReward: Math.round(xpReward*3.5), goldReward: scaleRange(3.5) },
  };
}

// Monster visual tiers:
//   tierNames  1 = Common/Uncommon, 2 = Rare, 3 = Epic/Legendary
//   tierImages Tier 3 falls back to Tier 2, then Tier 1. Tier 2 falls back to Tier 1.
//   tier3Oversized: 1 makes only the Epic/Legendary version oversized.
const ENEMIES = [
  {
    order: 1,
    id: 'rat',
    tierNames: { 1: 'RAT', 2: 'CAVE RAT', 3: 'GIANT RAT' },
    level: 1,
    maxHp: 20,
    att: 5,
    speed: 6,
    xpReward: 20,
    goldReward: [3, 6],
    emoji: '🐀',
    color: '#4ade80',
    tierImages: { 1: 'enemies/rat.webp', 2: 'enemies/rat2.webp', 3: 'enemies/rat3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    tier3Oversized: 0,
    unitSet: [1],
  },
  {
    order: 2,
    id: 'boar',
    tierNames: { 1: 'BOAR', 2: 'IRONHIDE BOAR', 3: 'GIANT BOAR' },
    level: 1,
    maxHp: 30,
    att: 4,
    speed: 4,
    xpReward: 25,
    goldReward: [3, 6],
    emoji: '🐗',
    color: '#4ade80',
    tierImages: { 1: 'enemies/boar.webp', 2: 'enemies/boar2.webp', 3: 'enemies/boar3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 0,
    unitSet: [1],
  },
  {
    order: 3,
    id: 'kobold',
    tierNames: { 1: 'KOBOLD MINER', 2: 'KOBOLD WARRIOR', 3: 'KOBOLD BOSS' },
    level: 2,
    maxHp: 35,
    att: 9,
    speed: 5,
    xpReward: 25,
    goldReward: [3, 9],
    emoji: '🦇',
    color: '#4ade80',
    tierImages: { 1: 'enemies/kobold.webp', 2: 'enemies/kobold2.webp', 3: 'enemies/kobold3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    unitSet: [1, 2],
  },
  {
    order: 4,
    id: 'goblin',
    tierNames: { 1: 'GOBLIN SPEARMAN', 2: 'GOBLIN WARRIOR', 3: 'GOBLIN CHAMPION' },
    level: 2,
    maxHp: 40,
    att: 10,
    speed: 5,
    xpReward: 30,
    goldReward: [6, 9],
    emoji: '👺',
    color: '#4ade80',
    tierImages: { 1: 'enemies/goblin.webp', 2: 'enemies/goblin2.webp', 3: 'enemies/goblin3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    unitSet: [1, 2],
  },
  {
    order: 5,
    id: 'scarecrow',
    norarity: 1,
    tierNames: { 1: 'SCARECROW', 2: 'SCARECROW', 3: 'SCARECROW' },
    level: 3,
    maxHp: 50,
    att: 11,
    speed: 6,
    xpReward: 35,
    goldReward: [6, 12],
    emoji: '👿',
    color: '#f97316',
    tierImages: { 1: 'enemies/scarecrow.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    unitSet: [2, 3],
  },
  {
    order: 6,
    id: 'wolf',
    tierNames: { 1: 'WOLF', 2: 'DIRE WOLF', 3: 'MOONFANG' },
    level: 3,
    maxHp: 55,
    att: 12,
    speed: 5,
    xpReward: 40,
    goldReward: [9, 12],
    emoji: '👾',
    color: '#a855f7',
    tierImages: { 1: 'enemies/wolf.webp', 2: 'enemies/wolf2.webp', 3: 'enemies/wolf3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 0,
    unitSet: [2, 3],
  },
  {
    order: 7,
    id: 'harpy',
    tierNames: { 1: 'HARPY', 2: 'HARPY', 3: 'HARPY QUEEN' },
    level: 4,
    maxHp: 60,
    att: 15,
    speed: 5,
    xpReward: 45,
    goldReward: [9, 15],
    emoji: '🧌',
    color: '#ef4444',
    tierImages: { 1: 'enemies/harpy.webp', 2: null, 3: 'enemies/harpy3.webp' },
    facesRight: false,
    flying: 1,
    vertical: 1,
    unitSet: [3, 4],
  },
  {
    order: 8,
    id: 'centaur',
    tierNames: { 1: 'CENTAUR', 2: 'CENTAUR WARRIOR', 3: 'CENTAUR STORMLANCER' },
    level: 4,
    maxHp: 65,
    att: 18,
    speed: 5,
    xpReward: 50,
    goldReward: [9, 18],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/centaur.webp', 2: 'enemies/centaur2.webp', 3: 'enemies/centaur3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 0,
    unitSet: [2, 3, 4],
  },

{
    order: 9,
    id: 'bandit',
    tierNames: { 1: 'BANDIT HENCHMAN', 2: 'BANDIT RAIDER', 3: 'BANDIT CHAMPION' },
    level: 5,
    maxHp: 70,
    att: 25,
    speed: 6,
    xpReward: 75,
    goldReward: [12, 18],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/bandit.webp', 2: 'enemies/bandit2.webp', 3: 'enemies/bandit3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    unitSet: [3, 4, 5],
  },
{
    order: 10,
    id: 'banditboss',
    tierNames: { 1: 'BANDIT LEADER', 2: 'BANDIT BOSS', 3: 'BANDIT OVERLORD' },
    level: 8,
    maxHp: 80,
    att: 30,
    speed: 5,
    xpReward: 100,
    goldReward: [50, 70],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/banditboss.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5],
},

{
    order: 11,
    id: 'spider',
    tierNames: { 1: 'SPIDER', 2: 'VENOMOUS SPIDER', 3: 'SPIDER QUEEN' },
    level: 5,
    maxHp: 70,
    att: 20,
    speed: 6,
    xpReward: 75,
    goldReward: [21, 27],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/spider.webp', 2: 'enemies/spider2.webp', 3: 'enemies/spider3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [6],
},
{
    order: 12,
    id: 'bogwitch',
    norarity: 1,
    tierNames: { 1: 'BOG WITCH', 2: 'BOG WITCH', 3: 'BOG WITCH' },
    level: 6,
    maxHp: 75,
    att: 25,
    speed: 6,
    xpReward: 75,
    goldReward: [21, 27],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/bogwitch.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [6],


  },

{
    order: 13,
    id: 'myconid',
    norarity: 1,
    tierNames: { 1: 'MYCONID', 2: 'MYCONID', 3: 'MYCONID' },
    level: 6,
    maxHp: 80,
    att: 30,
    speed: 7,
    xpReward: 80,
    goldReward: [24, 30],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/myconid.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [6, 7],


  },
{
    order: 14,
    id: 'dryad',
    norarity: 1,
    tierNames: { 1: 'DRYAD', 2: 'DRYAD', 3: 'DRYAD' },
    level: 7,
    maxHp: 85,
    att: 30,
    speed: 6,
    xpReward: 85,
    goldReward: [24, 30],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/dryad.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [6, 7],


  },

{
    order: 15,
    id: 'lizardman',
    tierNames: { 1: 'LIZARDMAN', 2: 'LIZARDMAN WARRIOR', 3: 'LIZARDMAN CHAMPION' },
    level: 7,
    maxHp: 90,
    att: 35,
    speed: 6,
    xpReward: 90,
    goldReward: [27, 33],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/lizardman.webp', 2: 'enemies/lizardman2.webp', 3: 'enemies/lizardman3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [8],


  },

{
    order: 16,
    id: 'werewolf',
    norarity: 1,
    tierNames: { 1: 'WEREWOLF', 2: 'WEREWOLF', 3: 'WEREWOLF' },
    level: 8,
    maxHp: 95,
    att: 30,
    speed: 4,
    xpReward: 95,
    goldReward: [27, 33],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/werewolf.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [8, 9],


  },

{
    order: 17,
    id: 'basilisk',
    norarity: 1,
    tierNames: { 1: 'BASILISK', 2: 'BASILISK', 3: 'BASILISK' },
    level: 8,
    maxHp: 100,
    att: 45,
    speed: 7,
    xpReward: 100,
    goldReward: [30, 36],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/basilisk.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [9],


  },
{
    order: 18,
    id: 'troll',
    tierNames: { 1: 'TROLL', 2: 'ROCKHIDE TROLL', 3: 'ELDER TROLL' },
    level: 9,
    maxHp: 110,
    att: 50,
    speed: 7,
    xpReward: 105,
    goldReward: [30, 39],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/troll.webp', 2: 'enemies/troll2.webp', 3: 'enemies/troll3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [9, 10],


  },

{
    order: 19,
    id: 'wendigo',
    norarity: 1,
    tierNames: { 1: 'WENDIGO', 2: 'WENDIGO', 3: 'WENDIGO' },
    level: 9,
    maxHp: 115,
    att: 50,
    speed: 6,
    xpReward: 110,
    goldReward: [33, 42],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/vendigo.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [8, 9, 10],


  },
{
    order: 20,
    id: 'ancienttreant',
    tierNames: { 1: 'ANCIENT TREANT', 2: 'ANCIENT TREANT', 3: 'ANCIENT TREANT' },
    level: 12,
    maxHp: 150,
    att: 70,
    speed: 6,
    xpReward: 150,
    goldReward: [100, 150],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/treant.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],


  },

{
    order: 21,
    id: 'frostbat',
    norarity: 1,
    tierNames: { 1: 'FROST BAT', 2: 'FROST BAT', 3: 'FROST BAT' },
    level: 10,
    maxHp: 120,
    att: 55,
    speed: 6,
    xpReward: 120,
    goldReward: [36, 45],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/frostbat.webp', 2: null, 3: null },
    facesRight: false,
    flying: 1,
    vertical: 0,
    oversized: 0,
    unitSet: [1, 3, 5],


  },

{
    order: 22,
    id: 'snowimp',
    tierNames: { 1: 'SNOW IMP', 2: 'FROST IMP', 3: 'BLIZZARD IMP' },
    level: 10,
    maxHp: 125,
    att: 55,
    speed: 6,
    xpReward: 120,
    goldReward: [30, 48],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/snowimp.webp', 2: 'enemies/snowimp2.webp', 3: 'enemies/snowimp3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [2, 4, 6],


  },

{
    order: 23,
    id: 'frostwolf',
    norarity: 1,
    tierNames: { 1: 'FROSTFANG WOLF', 2: 'FROSTFANG WOLF', 3: 'FROSTFANG WOLF' },
    level: 11,
    maxHp: 130,
    att: 50,
    speed: 5,
    xpReward: 125,
    goldReward: [33, 51],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/frostwolf.webp', 2: null , 3: null },
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [3, 5, 7],


  },
{
    order: 24,
    id: 'frostbear',
    tierNames: { 1: 'ICECLAW BEAR', 2: 'GLACIERHIDE BEAR', 3: 'ANCIENT BEAR' },
    level: 11,
    maxHp: 135,
    att: 60,
    speed: 6,
    xpReward: 130,
    goldReward: [36, 54],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/frostbear.webp', 2: 'enemies/frostbear2.webp' , 3: 'enemies/frostbear3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [4, 6, 8],


  },

{
    order: 25,
    id: 'crystalelemental',
    norarity: 1,
    tierNames: { 1: 'CRYSTAL ELEMENTAL', 2: 'CRYSTAL ELEMENTAL', 3: 'CRYSTAL ELEMENTAL' },
    level: 12,
    maxHp: 140,
    att: 65,
    speed: 6,
    xpReward: 135,
    goldReward: [39, 57],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/crystal.webp', 2: null , 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [5, 7, 9],


  },
{
    order: 26,
    id: 'icegargoyle',
    norarity: 1,
    tierNames: { 1: 'ICE GARGOYLE', 2: 'ICE GARGOYLE', 3: 'ICE GARGOYLE' },
    level: 12,
    maxHp: 145,
    att: 60,
    speed: 5,
    xpReward: 140,
    goldReward: [42, 60],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/icegargoyle.webp', 2: null , 3: null },
    facesRight: false,
    flying: 1,
    vertical: 1,
    oversized: 0,
    unitSet: [6, 8, 10],


  },

{
    order: 27,
    id: 'iceminotaur',
    tierNames: { 1: 'FROSTTHORN MINOTAUR', 2: 'GLACIERHORN MINOTAUR', 3: 'MINOTAUR CHAMPION' },
    level: 13,
    maxHp: 150,
    att: 70,
    speed: 6,
    xpReward: 145,
    goldReward: [45, 63],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/iceminotaur.webp', 2: 'enemies/iceminotaur2.webp' , 3: 'enemies/iceminotaur3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [1, 3, 5, 7],


  },

{
    order: 28,
    id: 'yeti',
    tierNames: { 1: 'YETI', 2: 'GLACIER YETI', 3: 'ANCIENT YETI' },
    level: 13,
    maxHp: 155,
    att: 85,
    speed: 7,
    xpReward: 150,
    goldReward: [48, 66],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/yeti.webp', 2: 'enemies/yeti2.webp' , 3: 'enemies/yeti3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [2, 4, 6, 8],


  },

{
    order: 29,
    id: 'stonetitan',
    norarity: 1,
    tierNames: { 1: 'STONE TITAN', 2: 'STONE TITAN', 3: 'STONE TITAN' },
    level: 14,
    maxHp: 160,
    att: 90,
    speed: 7,
    xpReward: 150,
    goldReward: [51, 69],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/stonetitan.webp', 2: null , 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [3, 5, 7, 9],


  },

{
    order: 30,
    id: 'icedragon',
    tierNames: { 1: 'WHITE DRAGON', 2: 'WHITE DRAGON', 3: 'WHITE DRAGON' },
    level: 18,
    maxHp: 200,
    att: 100,
    speed: 6,
    xpReward: 300,
    goldReward: [100, 120],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/icedragon.webp', 2: null , 3: null },
    facesRight: false,
    flying: 1,
    vertical: 0,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],


  },


{
    order: 31,
    id: 'orc',
    tierNames: { 1: 'ORC', 2: 'ORC WARRIOR', 3: 'URUK-HAI' },
    level: 14,
    maxHp: 160,
    att: 75,
    speed: 6,
    xpReward: 150,
    goldReward: [54, 72],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/orc.webp', 2: 'enemies/orc2.webp', 3: 'enemies/orc3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [1, 3, 5, 7],


  },

{
    order: 32,
    id: 'ogre',
    tierNames: { 1: 'OGRE GRUNT', 2: 'OGRE MAGI', 3: 'OGRE CHIEFTAIN' },
    level: 14,
    maxHp: 165,
    att: 80,
    speed: 6,
    xpReward: 155,
    goldReward: [57, 75],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/ogre.webp', 2: 'enemies/ogre2.webp', 3: 'enemies/ogre3.webp' },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [2, 4, 6, 8],


  },
{
    order: 33,
    id: 'magmajackal',
    norarity: 1,
    tierNames: { 1: 'MAGMA JACKAL', 2: 'MAGMA JACKAL', 3: 'MAGMA JACKAL' },
    level: 15,
    maxHp: 170,
    att: 85,
    speed: 6,
    xpReward: 160,
    goldReward: [60, 78],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/magmajackal.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [3, 5, 7, 9],


  },
{
    order: 34,
    id: 'salamander',
    norarity: 1,
    tierNames: { 1: 'SALAMANDER', 2: 'SALAMANDER', 3: 'SALAMANDER' },
    level: 15,
    maxHp: 175,
    att: 90,
    speed: 6,
    xpReward: 120,
    goldReward: [63, 81],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/salamander.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [5, 7, 9, 10],


  },

{
    order: 35,
    id: 'fireelemental',
    norarity: 1,
    tierNames: { 1: 'FIRE ELEMENTAL', 2: 'FIRE ELEMENTAL', 3: 'FIRE ELEMENTAL' },
    level: 16,
    maxHp: 180,
    att: 75,
    speed: 6,
    xpReward: 140,
    goldReward: [66, 84],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/fireelemental.webp', 2: null, 3: null },
    facesRight: false,
    flying: 1,
    vertical: 1,
    oversized: 0,
    unitSet: [1, 3, 6, 8, 10],


  },
{
    order: 36,
    id: 'manticore',
    norarity: 1,
    tierNames: { 1: 'MANTICORE', 2: 'MANTICORE', 3: 'MANTICORE' },
    level: 16,
    maxHp: 185,
    att: 80,
    speed: 6,
    xpReward: 145,
    goldReward: [69, 87],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/manticore.webp', 2: null, 3: null },
    facesRight: false,
    flying: 1,
    vertical: 0,
    oversized: 0,
    unitSet: [2, 4, 7, 9, 10],


  },
{
    order: 37,
    id: 'magmabeetle',
    norarity: 1,
    tierNames: { 1: 'MAGMA BEETLE', 2: 'MAGMA BEETLE', 3: 'MAGMA BEETLE' },
    level: 17,
    maxHp: 190,
    att: 90,
    speed: 7,
    xpReward: 150,
    goldReward: [72, 90],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/magmabeetle.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [1, 2, 3, 4, 5],


  },
{
    order: 38,
    id: 'emberwing',
    tierNames: { 1: 'EMBERWING SENTINEL', 2: 'FLAMEWING GUARDIAN', 3: 'SOLARWING CHAMPION' },
    level: 17,
    maxHp: 195,
    att: 75,
    speed: 5,
    xpReward: 155,
    goldReward: [75, 93],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/emberwing.webp', 2: 'enemies/emberwing2.webp', 3: 'enemies/emberwing3.webp' },
    facesRight: false,
    flying: 1,
    vertical: 0,
    oversized: 0,
    unitSet: [2, 3, 4, 5, 6],


  },

{
    order: 39,
    id: 'hydra',
    norarity: 1,
    tierNames: { 1: 'HYDRA', 2: 'HYDRA', 3: 'HYDRA' },
    level: 18,
    maxHp: 200,
    att: 85,
    speed: 6,
    xpReward: 160,
    goldReward: [78, 96],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/hydra.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [3, 4, 5, 6, 7, 8],


  },

{
    order: 40,
    id: 'reddragon',
    tierNames: { 1: 'RED DRAGON', 2: 'RED DRAGON', 3: 'RED DRAGON' },
    level: 21,
    maxHp: 250,
    att: 100,
    speed: 6,
    xpReward: 400,
    goldReward: [150, 200],
    emoji: '☠️',
    color: '#FFD700',
    tierImages: { 1: 'enemies/reddragon.webp', 2: null, 3:null },
    facesRight: false,
    flying: 1,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],


  },

{
    order: 41,
    id: 'darkmage',
    norarity: 1,
    tierNames: { 1: 'DARK MAGE', 2: 'DARK MAGE', 3: 'DARK MAGE' },
    level: 22,
    maxHp: 220,
    att: 95,
    speed: 5,
    xpReward: 180,
    goldReward: [85, 105],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/darkmage.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 0,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 42,
    id: 'deathknight',
    norarity: 1,
    tierNames: { 1: 'DEATH KNIGHT', 2: 'DEATH KNIGHT', 3: 'DEATH KNIGHT' },
    level: 22,
    maxHp: 230,
    att: 105,
    speed: 6,
    xpReward: 190,
    goldReward: [90, 110],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/deathknight.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 0,
    oversized: 0,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 43,
    id: 'phoenix',
    norarity: 1,
    tierNames: { 1: 'PHOENIX', 2: 'PHOENIX', 3: 'PHOENIX' },
    level: 23,
    maxHp: 240,
    att: 100,
    speed: 5,
    xpReward: 200,
    goldReward: [95, 115],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/phoenix.webp', 2: null, 3: null },
    facesRight: false,
    flying: 1,
    vertical: 0,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 44,
    id: 'frostgiant',
    norarity: 1,
    tierNames: { 1: 'FROST GIANT', 2: 'FROST GIANT', 3: 'FROST GIANT' },
    level: 23,
    maxHp: 260,
    att: 115,
    speed: 7,
    xpReward: 210,
    goldReward: [100, 120],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/frostgiant.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 45,
    id: 'valkyrie',
    norarity: 1,
    tierNames: { 1: 'VALKYRIE', 2: 'VALKYRIE', 3: 'VALKYRIE' },
    level: 24,
    maxHp: 250,
    att: 105,
    speed: 5,
    xpReward: 220,
    goldReward: [105, 125],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/valkyrie.webp', 2: null, 3: null },
    facesRight: false,
    flying: 1,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 46,
    id: 'wyvern',
    norarity: 1,
    tierNames: { 1: 'WYVERN', 2: 'WYVERN', 3: 'WYVERN' },
    level: 24,
    maxHp: 270,
    att: 110,
    speed: 5,
    xpReward: 230,
    goldReward: [110, 130],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/wyvern.webp', 2: null, 3: null },
    facesRight: false,
    flying: 1,
    vertical: 0,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 47,
    id: 'stormtitan',
    norarity: 1,
    tierNames: { 1: 'STORM TITAN', 2: 'STORM TITAN', 3: 'STORM TITAN' },
    level: 25,
    maxHp: 290,
    att: 120,
    speed: 6,
    xpReward: 245,
    goldReward: [115, 135],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/stormtitan.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 48,
    id: 'elderdragon',
    norarity: 1,
    tierNames: { 1: 'ELDER DRAGON', 2: 'ELDER DRAGON', 3: 'ELDER DRAGON' },
    level: 26,
    maxHp: 310,
    att: 125,
    speed: 6,
    xpReward: 260,
    goldReward: [120, 140],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/elderdragon.webp', 2: null, 3: null },
    facesRight: false,
    flying: 1,
    vertical: 0,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 49,
    id: 'voidlord',
    norarity: 1,
    tierNames: { 1: 'VOID LORD', 2: 'VOID LORD', 3: 'VOID LORD' },
    level: 27,
    maxHp: 340,
    att: 130,
    speed: 5,
    xpReward: 280,
    goldReward: [130, 155],
    emoji: '☠️',
    color: '#c4b5fd',
    tierImages: { 1: 'enemies/voidlord.webp', 2: null, 3: null },
    facesRight: false,
    flying: 0,
    vertical: 1,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
{
    order: 50,
    id: 'celestialdragon',
    norarity: 1,
    tierNames: { 1: 'CELESTIAL DRAGON', 2: 'CELESTIAL DRAGON', 3: 'CELESTIAL DRAGON' },
    level: 30,
    maxHp: 450,
    att: 150,
    speed: 5,
    xpReward: 800,
    goldReward: [300, 400],
    emoji: '☠️',
    color: '#fef3c7',
    tierImages: { 1: 'enemies/celestialdragon.webp', 2: null, 3: null },
    facesRight: false,
    flying: 1,
    vertical: 0,
    oversized: 1,
    unitSet: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },

];

ENEMIES.forEach(enemy => {
  enemy.rarityVersions = enemy.rarityVersions || enemyRarityVersions(
    enemy.maxHp,
    enemy.att,
    enemy.speed,
    enemy.xpReward,
    enemy.goldReward
  );
});
