// Adventurer's Guild quest definitions.
// Supported types: defeat_enemy, defeat_specific_enemy, correct_answer, reach_streak, defeat_tier, defeat_boss.
// Chained quests use chained:1 and either targets:[...] or target + chainLength.
// Reward arrays follow each chain stage. Scalar itemRarity is granted only on the final stage.
const QUESTS = [
  {
    id: 'first_hunt',
    title: 'GREAT HUNT',
    description: 'Defeat 5 enemies.',
    type: 'defeat_enemy',
    chained: 1,
    targets: [5, 10, 20, 40, 80],
    minLevel: 1,
    runsNeeded: 0,
    repeatable: 0,
    reward: { gold: [25, 35, 50, 100, 0], itemRarity: 4 },
  },
  {
    id: 'word_scholar',
    title: 'WORD SCHOLAR',
    description: 'Answer 30 questions correctly.',
    type: 'correct_answer',
    target: 30,
    minLevel: 2,
    runsNeeded: 0,
    repeatable: 1,
    reward: { gold: 25, essence: 2 },
  },
  {
    id: 'steady_hand',
    title: 'STEADY HAND',
    description: 'Reach a 10 answer streak.',
    type: 'reach_streak',
    target: 10,
    minLevel: 2,
    runsNeeded: 1,
    repeatable: 1,
    reward: { gold:25, essence: 3 },
  },
  {
    id: 'rare_game',
    title: 'RARE GAME',
    description: 'Defeat 3 Tier 2 or higher minions.',
    type: 'defeat_tier',
    chained: 1,
    targets: [3, 6, 12, 24, 50],
    minTier: 2,
    excludeBoss: 1,
    minLevel: 3,
    runsNeeded: 1,
    repeatable: 0,
    reward:  { gold: [25, 50, 100, 200, 0], itemRarity: 5 },
  },
  {
    id: 'boss_hunter',
    title: 'BOSS HUNTER',
    description: 'Defeat biome boss(es)',
    type: 'defeat_boss',
    chained: 1,
    targets: [1, 3, 5, 15, 30],
    minLevel: 4,
    repeatable: 0,
    reward: { gold: [50, 100, 200, 300, 0], essence: [5, 10, 20, 40, 0], itemRarity: [3, 0, 4, 0, 5] },
  },
  {
    id: 'boar_hunt',
    title: 'BOAR HUNT',
    description: 'Defeat a Boar.',
    type: 'defeat_specific_enemy',
    enemyId: 'boar',
    target: 1,
    minLevel: 2,
    runsNeeded: 0,
    repeatable: 0,
    reward: { gold: 45, essence: 1 },
  },
  {
    id: 'wolf_hunt',
    title: 'WOLF HUNT',
    description: 'Defeat a Wolf.',
    type: 'defeat_specific_enemy',
    enemyId: 'wolf',
    target: 1,
    minLevel: 2,
    runsNeeded: 2,
    repeatable: 0,
    prerequisite: 'boar_hunt',
    reward: { gold: 50, essence: 1 },
  },
  {
    id: 'harpy_hunt',
    title: 'HARPY HUNT',
    description: 'Defeat a Harpy.',
    type: 'defeat_specific_enemy',
    enemyId: 'harpy',
    target: 1,
    minLevel: 3,
    runsNeeded: 3,
    repeatable: 0,
    prerequisite: 'wolf_hunt',
    reward: { gold: 55, essence: 1 },
  },
  {
    id: 'spider_hunt',
    title: 'SPIDER HUNT',
    description: 'Defeat a Spider.',
    type: 'defeat_specific_enemy',
    enemyId: 'spider',
    target: 1,
    minLevel: 3,
    runsNeeded: 3,
    repeatable: 0,
    prerequisite: 'harpy_hunt',
    reward: { gold: 60, essence: 2 },
  },
  {
    id: 'dryad_hunt',
    title: 'DRYAD HUNT',
    description: 'Defeat a Dryad.',
    type: 'defeat_specific_enemy',
    enemyId: 'dryad',
    target: 1,
    minLevel: 4,
    runsNeeded: 3,
    repeatable: 0,
    prerequisite: 'spider_hunt',
    reward: { gold: 65, essence: 2 },
  },
  {
    id: 'lizardman_hunt',
    title: 'LIZARDMAN HUNT',
    description: 'Defeat a Lizardman.',
    type: 'defeat_specific_enemy',
    enemyId: 'lizardman',
    target: 1,
    minLevel: 4,
    runsNeeded: 4,
    repeatable: 0,
    prerequisite: 'dryad_hunt',
    reward: { gold: 70, essence: 2 },
  },
  {
    id: 'basilisk_hunt',
    title: 'BASILISK HUNT',
    description: 'Defeat a Basilisk.',
    type: 'defeat_specific_enemy',
    enemyId: 'basilisk',
    target: 1,
    minLevel: 5,
    runsNeeded: 4,
    repeatable: 0,
    prerequisite: 'lizardman_hunt',
    reward: { gold: 80, essence: 2 },
  },
  {
    id: 'frost_bat_hunt',
    title: 'FROST BAT HUNT',
    description: 'Defeat a Frost Bat.',
    type: 'defeat_specific_enemy',
    enemyId: 'frostbat',
    target: 1,
    minLevel: 6,
    runsNeeded: 4,
    repeatable: 0,
    prerequisite: 'basilisk_hunt',
    reward: { gold: 90, essence: 3 },
  },
  {
    id: 'frost_bear_hunt',
    title: 'FROST BEAR HUNT',
    description: 'Defeat an Iceclaw Bear.',
    type: 'defeat_specific_enemy',
    enemyId: 'frostbear',
    target: 1,
    minLevel: 6,
    runsNeeded: 4,
    repeatable: 0,
    prerequisite: 'frost_bat_hunt',
    reward: { gold: 100, essence: 3 },
  },
  {
    id: 'ice_minotaur_hunt',
    title: 'ICE MINOTAUR HUNT',
    description: 'Defeat a Frostthorn Minotaur.',
    type: 'defeat_specific_enemy',
    enemyId: 'iceminotaur',
    target: 1,
    minLevel: 7,
    runsNeeded: 5,
    repeatable: 0,
    prerequisite: 'frost_bear_hunt',
    reward: { gold: 110, essence: 4 },
  },
  {
    id: 'yeti_hunt',
    title: 'YETI HUNT',
    description: 'Defeat a Yeti.',
    type: 'defeat_specific_enemy',
    enemyId: 'yeti',
    target: 1,
    minLevel: 8,
    runsNeeded: 5,
    repeatable: 0,
    prerequisite: 'ice_minotaur_hunt',
    reward: { gold: 120, essence: 4 },
  },
  {
    id: 'orc_hunt',
    title: 'ORC HUNT',
    description: 'Defeat an Orc.',
    type: 'defeat_specific_enemy',
    enemyId: 'orc',
    target: 1,
    minLevel: 8,
    runsNeeded: 5,
    repeatable: 0,
    prerequisite: 'yeti_hunt',
    reward: { gold: 130, essence: 4 },
  },
  {
    id: 'magma_jackal_hunt',
    title: 'MAGMA JACKAL HUNT',
    description: 'Defeat a Magma Jackal.',
    type: 'defeat_specific_enemy',
    enemyId: 'magmajackal',
    target: 1,
    minLevel: 9,
    runsNeeded: 5,
    repeatable: 0,
    prerequisite: 'orc_hunt',
    reward: { gold: 140, essence: 4 },
  },
  {
    id: 'hydra_hunt',
    title: 'HYDRA HUNT',
    description: 'Defeat a Hydra.',
    type: 'defeat_specific_enemy',
    enemyId: 'hydra',
    target: 1,
    minLevel: 10,
    runsNeeded: 6,
    repeatable: 0,
    prerequisite: 'magma_jackal_hunt',
    reward: { gold: 160, essence: 5 },
  },
];
