/* ─────────────────────────────────────────────────────────────────
   WORD CONTEST — KELIME HAVUZU
   Format: { en, tr, grade, diff, unit }
   diff  : 1=easy | 2=medium | 3=hard
   grade : sınıf (6/7/8 | 0=özel kategori)
   unit  : ünite numarası (11=Animals, 12=Foods&Drinks)
   ───────────────────────────────────────────────────────────────── */
const WORD_BANK = [

  // ─── GRADE 7 UNIT 1 ──────────────────────────────────────────────────────────
  { en:'ATTRACTIVE',   tr:'ÇEKİCİ',            grade:7, diff:2, unit:1 },
  { en:'CLUMSY',       tr:'SAKAR',              grade:7, diff:2, unit:1 },
  { en:'EASYGOING',    tr:'UYUMLU',             grade:7, diff:2, unit:1 },
  { en:'FORGETFUL',    tr:'UNUTKAN',            grade:7, diff:3, unit:1 },
  { en:'GENEROUS',     tr:'CÖMERT',             grade:7, diff:1, unit:1 },
  { en:'HONEST',       tr:'DÜRÜST',             grade:7, diff:1, unit:1 },
  { en:'OUTGOING',     tr:'GİRİŞKEN',           grade:7, diff:1, unit:1 },
  { en:'OVERWEIGHT',   tr:'KİLOLU',             grade:7, diff:1, unit:1 },
  { en:'PUNCTUAL',     tr:'DAKİK',              grade:7, diff:2, unit:1 },
  { en:'SELFISH',      tr:'BENCİL',             grade:7, diff:1, unit:1 },
  { en:'SLIM',         tr:'ZAYIF',              grade:7, diff:2, unit:1 },
  { en:'STUBBORN',     tr:'İNATÇI',             grade:7, diff:3, unit:1 },
  { en:'THOUGHTFUL',   tr:'DÜŞÜNCELI',          grade:7, diff:3, unit:1 },
  { en:'WELL BUILT',   tr:'ATLETİK',            grade:7, diff:1, unit:1 },
  { en:'APPEARANCE',   tr:'GÖRÜNÜŞ',            grade:7, diff:3, unit:1 },
  { en:'PERSONALITY',  tr:'KİŞİLİK',            grade:7, diff:3, unit:1 },
  { en:'CLEVER',       tr:'ZEKI',               grade:7, diff:1, unit:1 },
  { en:'PLUMP',        tr:'TOMBUL',             grade:7, diff:2, unit:1 },
  { en:'INTELLIGENT',  tr:'ZEKI',               grade:7, diff:3, unit:1 },
  { en:'TALL',         tr:'UZUN BOYLU',         grade:7, diff:1, unit:1 },
  { en:'POLITE',       tr:'NAZIK',              grade:7, diff:2, unit:1 },
  { en:'FRIENDLY',     tr:'ARKADAŞ CANLISI',    grade:7, diff:1, unit:1 },
  { en:'CHEERFUL',     tr:'NEŞELİ',             grade:7, diff:2, unit:1 },
  { en:'GET ON WELL',  tr:'İYİ GEÇİNMEK',       grade:7, diff:3, unit:1 },
  { en:'BLOND',        tr:'SARIŞIN',            grade:7, diff:1, unit:1 },
  { en:'CURLY',        tr:'KIVIRCIK',           grade:7, diff:1, unit:1 },
  { en:'RELIABLE',     tr:'GÜVENİLİR',          grade:7, diff:3, unit:1 },
  { en:'STRAIGHT',     tr:'DÜZ (SAÇ)',          grade:7, diff:3, unit:1 },
  { en:'WAVY',         tr:'DALGALI',            grade:7, diff:2, unit:1 },
  { en:'BALD',         tr:'KEL',                grade:7, diff:1, unit:1 },
  { en:'STUMPY',       tr:'BODUR',              grade:7, diff:2, unit:1 },
  { en:'STINGY',       tr:'CİMRİ',              grade:7, diff:2, unit:1 },
  { en:'MOUSTACHE',    tr:'BIYIK',              grade:7, diff:2, unit:1 },
  { en:'SOCIABLE',     tr:'SOSYAL',             grade:7, diff:2, unit:1 },
  { en:'ADVENTUROUS',  tr:'MACERAci',           grade:7, diff:3, unit:1 },
  { en:'TALENTED',     tr:'YETENEKLİ',          grade:7, diff:3, unit:1 },
  { en:'BEARD',        tr:'SAKAL',              grade:7, diff:1, unit:1 },
  { en:'BEAUTIFUL',    tr:'GÜZEL',              grade:7, diff:1, unit:1 },
  { en:'GLASSES',      tr:'GÖZLÜK',             grade:7, diff:2, unit:1 },
  { en:'HANDSOME',     tr:'YAKIŞIKLI',          grade:7, diff:2, unit:1 },
  { en:'MIDDLE AGED',  tr:'ORTA YAŞLI',         grade:7, diff:3, unit:1 },
  { en:'UGLY',         tr:'ÇİRKİN',             grade:7, diff:1, unit:1 },

  // ─── GRADE 7 UNIT 2 ──────────────────────────────────────────────────────────
  { en:'ACHIEVE',      tr:'BAŞARMAK',           grade:7, diff:2, unit:2 },
  { en:'BEAT',         tr:'YENMEK',             grade:7, diff:1, unit:2 },
  { en:'DRAW',         tr:'BERABERLİK',         grade:7, diff:1, unit:2 },
  { en:'EQUIPMENT',    tr:'EKİPMAN',            grade:7, diff:2, unit:2 },
  { en:'GO ON A DIET', tr:'DİYETE GİRMEK',      grade:7, diff:2, unit:2 },
  { en:'DEFEAT',       tr:'YENMEK',             grade:7, diff:2, unit:2 },
  { en:'INDOOR',       tr:'KAPALI ALAN',         grade:7, diff:1, unit:2 },
  { en:'OUTDOOR',      tr:'AÇIK ALAN',           grade:7, diff:1, unit:2 },
  { en:'INJURY',       tr:'SAKATLK',            grade:7, diff:2, unit:2 },
  { en:'LOSE',         tr:'KAYBETMEK',          grade:7, diff:1, unit:2 },
  { en:'SHUTTLECOCK',  tr:'TÜY TOP',            grade:7, diff:3, unit:2 },
  { en:'SPECTATOR',    tr:'SEYİRCİ',            grade:7, diff:3, unit:2 },
  { en:'SUCCESS',      tr:'BAŞARI',             grade:7, diff:2, unit:2 },
  { en:'TRAIN',        tr:'ANTRENMAN YAPMAK',   grade:7, diff:1, unit:2 },
  { en:'POOL',         tr:'HAVUZ',              grade:7, diff:1, unit:2 },
  { en:'GOGGLES',      tr:'YÜZÜCÜ GÖZLÜĞÜ',    grade:7, diff:2, unit:2 },
  { en:'ARCHERY',      tr:'OKÇULUK',            grade:7, diff:2, unit:2 },
  { en:'GLOVES',       tr:'ELDİVEN',            grade:7, diff:1, unit:2 },
  { en:'WEIGHT',       tr:'AĞIRLIK',            grade:7, diff:1, unit:2 },
  { en:'HOOP',         tr:'ÇEMBER',             grade:7, diff:2, unit:2 },
  { en:'WRESTLING',    tr:'GÜREŞ',              grade:7, diff:2, unit:2 },
  { en:'HOME TEAM',    tr:'EV SAHİBİ TAKIM',    grade:7, diff:1, unit:2 },
  { en:'GUEST TEAM',   tr:'MİSAFİR TAKIM',      grade:7, diff:2, unit:2 },
  { en:'HELMET',       tr:'KASK',               grade:7, diff:2, unit:2 },
  { en:'INDIVIDUAL',   tr:'BİREYSEL',           grade:7, diff:3, unit:2 },
  { en:'RAFTING',      tr:'RAFTİNG',            grade:7, diff:2, unit:2 },
  { en:'NEVER',        tr:'HİÇBİR ZAMAN',       grade:7, diff:1, unit:2 },
  { en:'WIN',          tr:'KAZANMAK',           grade:7, diff:1, unit:2 },
  { en:'REFEREE',      tr:'HAKEM',              grade:7, diff:2, unit:2 },
  { en:'JOGGING',      tr:'KOŞU',               grade:7, diff:1, unit:2 },
  { en:'SKATING',      tr:'PATEN KAYMA',         grade:7, diff:1, unit:2 },
  { en:'ROLLERBLADING',tr:'PALETLI PATEN',       grade:7, diff:3, unit:2 },
  { en:'SKIING',       tr:'KAYAK',              grade:7, diff:1, unit:2 },
  { en:'GOAL KEEPER',  tr:'KALECI',             grade:7, diff:2, unit:2 },
  { en:'SADDLE',       tr:'EĞR',               grade:7, diff:2, unit:2 },
  { en:'COMPETE',      tr:'REKABET ETMEK',       grade:7, diff:2, unit:2 },

  // ─── GRADE 7 UNIT 3 ──────────────────────────────────────────────────────────
  { en:'ALONE',        tr:'YALNIZ',             grade:7, diff:1, unit:3 },
  { en:'AWARD',        tr:'ÖDÜL',               grade:7, diff:1, unit:3 },
  { en:'DIED',         tr:'ÖLDÜ',               grade:7, diff:1, unit:3 },
  { en:'MOVE',         tr:'TAŞINMAK',           grade:7, diff:1, unit:3 },
  { en:'GET MARRIED',  tr:'EVLENMEK',           grade:7, diff:1, unit:3 },
  { en:'GROW UP',      tr:'BÜYÜMEK',            grade:7, diff:1, unit:3 },
  { en:'AUTHOR',       tr:'YAZAR',              grade:7, diff:1, unit:3 },
  { en:'FAMOUS',       tr:'ÜNLÜ',               grade:7, diff:1, unit:3 },
  { en:'BORN',         tr:'DOĞMAK',             grade:7, diff:1, unit:3 },
  { en:'LIGHT BULB',   tr:'AMPUL',              grade:7, diff:1, unit:3 },
  { en:'SCIENTIST',    tr:'BİLİM İNSANI',       grade:7, diff:1, unit:3 },
  { en:'IMPORTANT',    tr:'ÖNEMLİ',             grade:7, diff:1, unit:3 },
  { en:'MEDICINE',     tr:'İLAÇ',               grade:7, diff:1, unit:3 },
  { en:'PRIZE',        tr:'ÖDÜL',               grade:7, diff:1, unit:3 },
  { en:'BRILLIANT',    tr:'DAHİ / PARLAK',       grade:7, diff:2, unit:3 },
  { en:'GRADUATE',     tr:'MEZUN OLMAK',         grade:7, diff:2, unit:3 },
  { en:'GET ENGAGED',  tr:'NİŞANLANMAK',        grade:7, diff:2, unit:3 },
  { en:'WELL KNOWN',   tr:'ÇOK BİLİNEN',        grade:7, diff:2, unit:3 },
  { en:'RAISE KIDS',   tr:'ÇOCUK YETİŞTİRMEK',  grade:7, diff:2, unit:3 },
  { en:'EDUCATION',    tr:'EĞİTİM',             grade:7, diff:2, unit:3 },
  { en:'ADOPT',        tr:'EVLAT EDİNMEK',       grade:7, diff:2, unit:3 },
  { en:'DISCOVER',     tr:'KEŞFETMEK',           grade:7, diff:2, unit:3 },
  { en:'INVENT',       tr:'İCAT ETMEK',          grade:7, diff:2, unit:3 },
  { en:'TALENTED',     tr:'YETENEKLİ',           grade:7, diff:2, unit:3 },
  { en:'ABROAD',       tr:'YURT DIŞI',           grade:7, diff:2, unit:3 },
  { en:'COMPANY',      tr:'ŞİRKET',             grade:7, diff:2, unit:3 },
  { en:'SUCCESSFUL',   tr:'BAŞARILI',            grade:7, diff:2, unit:3 },
  { en:'EXTRAORDINARY',tr:'OLAĞANÜSTÜ',          grade:7, diff:3, unit:3 },
  { en:'COMPOSE',      tr:'BESTELEMEK',          grade:7, diff:3, unit:3 },
  { en:'RESEARCH',     tr:'ARAŞTIRMA',           grade:7, diff:3, unit:3 },
  { en:'EAGER',        tr:'İSTEKLİ',             grade:7, diff:3, unit:3 },
  { en:'SCHOLARSHIP',  tr:'BURS',               grade:7, diff:3, unit:3 },
  { en:'ACHIEVEMENT',  tr:'BAŞARI',             grade:7, diff:3, unit:3 },
  { en:'OCCUPATION',   tr:'MESLEK',             grade:7, diff:3, unit:3 },
  { en:'EXHIBITION',   tr:'SERGİ',              grade:7, diff:3, unit:3 },
  { en:'CHEMIST',      tr:'KİMYAGER',           grade:7, diff:3, unit:3 },

  // ─── GRADE 7 UNIT 4 ──────────────────────────────────────────────────────────
  { en:'ATTACK',       tr:'SALDIRMAK',           grade:7, diff:1, unit:4 },
  { en:'AFRAID',       tr:'KORKMUŞ',             grade:7, diff:1, unit:4 },
  { en:'CAGE',         tr:'KAFES',               grade:7, diff:1, unit:4 },
  { en:'HARM',         tr:'ZARAR VERMEK',         grade:7, diff:1, unit:4 },
  { en:'HUMAN',        tr:'İNSAN',               grade:7, diff:1, unit:4 },
  { en:'HUNT',         tr:'AV YAPMAK',           grade:7, diff:1, unit:4 },
  { en:'SURVIVE',      tr:'HAYATTA KALMAK',       grade:7, diff:1, unit:4 },
  { en:'INSECT',       tr:'BÖCEK',               grade:7, diff:1, unit:4 },
  { en:'DANGEROUS',    tr:'TEHLİKELİ',           grade:7, diff:1, unit:4 },
  { en:'FUR',          tr:'KÜRK',                grade:7, diff:1, unit:4 },
  { en:'CLAW',         tr:'PENÇE',               grade:7, diff:1, unit:4 },
  { en:'WING',         tr:'KANAT',               grade:7, diff:1, unit:4 },
  { en:'FEATHER',      tr:'TÜY',                 grade:7, diff:1, unit:4 },
  { en:'TAIL',         tr:'KUYRUK',              grade:7, diff:1, unit:4 },
  { en:'SKIN',         tr:'DERİ',                grade:7, diff:1, unit:4 },
  { en:'DESERT',       tr:'ÇÖL',                 grade:7, diff:1, unit:4 },
  { en:'MOUNTAIN',     tr:'DAĞ',                 grade:7, diff:1, unit:4 },
  { en:'FOREST',       tr:'ORMAN',               grade:7, diff:1, unit:4 },
  { en:'OCEAN',        tr:'OKYANUS',             grade:7, diff:1, unit:4 },
  { en:'JUNGLE',       tr:'TROPIKAL ORMAN',       grade:7, diff:1, unit:4 },
  { en:'POISONOUS',    tr:'ZEHİRLİ',             grade:7, diff:2, unit:4 },
  { en:'ENORMOUS',     tr:'DEV GİBİ',            grade:7, diff:2, unit:4 },
  { en:'EXTINCT',      tr:'NESLİ TÜKENMİŞ',      grade:7, diff:2, unit:4 },
  { en:'HABITAT',      tr:'YAŞAM ALANI',          grade:7, diff:2, unit:4 },
  { en:'DONATE',       tr:'BAĞIŞ YAPMAK',         grade:7, diff:2, unit:4 },
  { en:'WILD LIFE',    tr:'YABAN HAYATI',          grade:7, diff:2, unit:4 },
  { en:'ENDANGERED',   tr:'TEHLİKE ALTINDA',       grade:7, diff:2, unit:4 },
  { en:'CARNIVORE',    tr:'ETÇİL',               grade:7, diff:2, unit:4 },
  { en:'PREY',         tr:'AV',                  grade:7, diff:2, unit:4 },
  { en:'HERBIVORE',    tr:'OTÇİL',               grade:7, diff:2, unit:4 },
  { en:'OMNIVORE',     tr:'HEPÇİL',              grade:7, diff:2, unit:4 },
  { en:'STRIPE',       tr:'ÇİZGİ',               grade:7, diff:2, unit:4 },
  { en:'SAVANNAH',     tr:'SAVAN',               grade:7, diff:2, unit:4 },
  { en:'TRUNK',        tr:'HORTUM',              grade:7, diff:2, unit:4 },
  { en:'HORN',         tr:'BOYNUZ',              grade:7, diff:2, unit:4 },
  { en:'AMPHIBIAN',    tr:'İKİYASAMLI',           grade:7, diff:3, unit:4 },
  { en:'IVORY',        tr:'FİL DİŞİ',            grade:7, diff:3, unit:4 },
  { en:'REPTILE',      tr:'SÜRÜNGEN',            grade:7, diff:2, unit:4 },

  // ─── GRADE 7 UNIT 5 ──────────────────────────────────────────────────────────
  { en:'APPEAR',       tr:'GÖRÜNMEK',            grade:7, diff:3, unit:5 },
  { en:'PREFERENCE',   tr:'TERCİH',              grade:7, diff:2, unit:5 },
  { en:'VIOLENCE',     tr:'ŞİDDET',              grade:7, diff:3, unit:5 },
  { en:'SERIES',       tr:'DİZİ',                grade:7, diff:1, unit:5 },
  { en:'TALK SHOW',    tr:'TALK SHOW',           grade:7, diff:1, unit:5 },
  { en:'EDUCATIONAL',  tr:'EĞİTİCİ',             grade:7, diff:3, unit:5 },
  { en:'MOVIE',        tr:'FİLM',                grade:7, diff:1, unit:5 },
  { en:'DOCUMENTARY',  tr:'BELGESEL',            grade:7, diff:2, unit:5 },
  { en:'AMUSING',      tr:'EĞLENCELİ',           grade:7, diff:2, unit:5 },
  { en:'DISCUSSION',   tr:'TARTIŞMA',            grade:7, diff:3, unit:5 },
  { en:'DEBATE',       tr:'TARTIŞMA',            grade:7, diff:3, unit:5 },
  { en:'ENTERTAINING', tr:'EĞLENCELİ',           grade:7, diff:3, unit:5 },
  { en:'COMMERCIAL',   tr:'REKLAM',              grade:7, diff:3, unit:5 },
  { en:'COOKERY',      tr:'YEMEK PİŞİRME',       grade:7, diff:1, unit:5 },
  { en:'INTERESTING',  tr:'İLGİNÇ',              grade:7, diff:2, unit:5 },
  { en:'NEWS',         tr:'HABER',               grade:7, diff:1, unit:5 },
  { en:'CARTOON',      tr:'ÇİZGİ FİLM',          grade:7, diff:1, unit:5 },
  { en:'EXCITING',     tr:'HEYECAN VERİCİ',       grade:7, diff:2, unit:5 },
  { en:'QUIZ SHOW',    tr:'YARIŞMA PROGRAMI',     grade:7, diff:1, unit:5 },
  { en:'THRILLER',     tr:'GERİLİM',             grade:7, diff:3, unit:5 },
  { en:'BORING',       tr:'SIKI',                grade:7, diff:1, unit:5 },
  { en:'REALITY SHOW', tr:'REALİTE PROGRAMI',     grade:7, diff:2, unit:5 },
  { en:'HORROR',       tr:'KORKU',               grade:7, diff:1, unit:5 },
  { en:'COUCH POTATO', tr:'TV BAĞIMLISI',         grade:7, diff:2, unit:5 },
  { en:'SIT COM',      tr:'SİTKOM',              grade:7, diff:3, unit:5 },
  { en:'COMEDY',       tr:'KOMEDİ',              grade:7, diff:1, unit:5 },
  { en:'RIDICULOUS',   tr:'SAÇMA',               grade:7, diff:3, unit:5 },
  { en:'SOAP OPERA',   tr:'PEMBE DİZİ',           grade:7, diff:3, unit:5 },
  { en:'ADVENTURE',    tr:'MACERA',              grade:7, diff:2, unit:5 },
  { en:'REMOTE CONTROL',tr:'UZAKTAN KUMANDA',    grade:7, diff:2, unit:5 },
  { en:'TELLY ADDICT', tr:'TV BAĞIMLISI',         grade:7, diff:2, unit:5 },
  { en:'DIRECTOR',     tr:'YÖNETMEN',            grade:7, diff:1, unit:5 },
  { en:'EPISODE',      tr:'BÖLÜM',               grade:7, diff:2, unit:5 },

  // ─── GRADE 7 UNIT 6 ──────────────────────────────────────────────────────────
  { en:'ARRANGE',      tr:'DÜZENLEMEK',           grade:7, diff:3, unit:6 },
  { en:'ATTEND',       tr:'KATILMAK',             grade:7, diff:2, unit:6 },
  { en:'BEVERAGE',     tr:'İÇECEK',              grade:7, diff:2, unit:6 },
  { en:'ORGANIZE',     tr:'DÜZENLEMEK',           grade:7, diff:2, unit:6 },
  { en:'DECORATE',     tr:'SÜSLEMEK',             grade:7, diff:2, unit:6 },
  { en:'FIREWORK',     tr:'HAVAİ FİŞEK',          grade:7, diff:2, unit:6 },
  { en:'GUEST LIST',   tr:'MİSAFİR LİSTESİ',      grade:7, diff:2, unit:6 },
  { en:'HOST',         tr:'EV SAHİBİ',            grade:7, diff:3, unit:6 },
  { en:'INVITE',       tr:'DAVET ETMEK',           grade:7, diff:2, unit:6 },
  { en:'ACCEPT',       tr:'KABUL ETMEK',           grade:7, diff:1, unit:6 },
  { en:'REFUSE',       tr:'REDDETMEK',            grade:7, diff:1, unit:6 },
  { en:'WRAP',         tr:'SARMAK',               grade:7, diff:3, unit:6 },
  { en:'CELEBRATE',    tr:'KUTLAMAK',             grade:7, diff:3, unit:6 },
  { en:'WEDDING',      tr:'DÜĞÜN',               grade:7, diff:2, unit:6 },
  { en:'BIRTHDAY',     tr:'DOĞUM GÜNÜ',           grade:7, diff:1, unit:6 },
  { en:'HALLOWEEN',    tr:'CADILLAR BAYRAMI',      grade:7, diff:1, unit:6 },
  { en:'FANCY DRESS',  tr:'KOSTÜM',              grade:7, diff:2, unit:6 },
  { en:'SLEEPOVER',    tr:'GECELEME PARTİSİ',     grade:7, diff:2, unit:6 },
  { en:'FIRST',        tr:'İLK',                 grade:7, diff:1, unit:6 },
  { en:'FINALLY',      tr:'SONUNDA',             grade:7, diff:2, unit:6 },
  { en:'WELCOME',      tr:'HOŞ GELDİNİZ',         grade:7, diff:2, unit:6 },
  { en:'APOLOGIZE',    tr:'ÖZÜR DİLEMEK',         grade:7, diff:3, unit:6 },
  { en:'FAREWELL',     tr:'VEDA',                grade:7, diff:3, unit:6 },
  { en:'PARADE',       tr:'GEÇİT TÖRENİ',         grade:7, diff:2, unit:6 },
  { en:'OFFER',        tr:'TEKLİF ETMEK',          grade:7, diff:3, unit:6 },
  { en:'SUGGEST',      tr:'ÖNERMEK',              grade:7, diff:3, unit:6 },
  { en:'PRESENT',      tr:'HEDİYE',              grade:7, diff:1, unit:6 },
  { en:'DATE',         tr:'TARİH',               grade:7, diff:1, unit:6 },
  { en:'TIME',         tr:'SAAT / ZAMAN',         grade:7, diff:1, unit:6 },
  { en:'PLACE',        tr:'YER',                 grade:7, diff:1, unit:6 },
  { en:'PREPARE',      tr:'HAZIRLAMAK',           grade:7, diff:3, unit:6 },
  { en:'CANDLE',       tr:'MUM',                 grade:7, diff:1, unit:6 },
  { en:'ORDER',        tr:'SİPARİŞ VERMEK',       grade:7, diff:2, unit:6 },
  { en:'WEAR',         tr:'GİYMEK',              grade:7, diff:2, unit:6 },

  // ─── GRADE 7 UNIT 7 ──────────────────────────────────────────────────────────
  { en:'BELIEVE',      tr:'İNANMAK',             grade:7, diff:3, unit:7 },
  { en:'CAREER',       tr:'KARİYER',             grade:7, diff:2, unit:7 },
  { en:'DREAM',        tr:'RÜYA',                grade:7, diff:1, unit:7 },
  { en:'EXCELLENT',    tr:'MÜKEMMEL',            grade:7, diff:3, unit:7 },
  { en:'GUESS',        tr:'TAHMİN ETMEK',         grade:7, diff:2, unit:7 },
  { en:'IMAGINE',      tr:'HAYAL ETMEK',          grade:7, diff:3, unit:7 },
  { en:'PEACEFUL',     tr:'HUZURLU',             grade:7, diff:2, unit:7 },
  { en:'PREDICT',      tr:'TAHMİN ETMEK',         grade:7, diff:3, unit:7 },
  { en:'PROBABLY',     tr:'MUHTEMELEN',           grade:7, diff:3, unit:7 },
  { en:'RECEIVE',      tr:'ALMAK',               grade:7, diff:3, unit:7 },
  { en:'SUCCESSFUL',   tr:'BAŞARILI',             grade:7, diff:2, unit:7 },
  { en:'MARRIAGE',     tr:'EVLİLİK',             grade:7, diff:2, unit:7 },
  { en:'FUTURE',       tr:'GELECEK',             grade:7, diff:1, unit:7 },
  { en:'GOOD LUCK',    tr:'İYİ ŞANSLAR',          grade:7, diff:1, unit:7 },
  { en:'BAD LUCK',     tr:'KÖTÜ ŞANS',            grade:7, diff:1, unit:7 },
  { en:'DROUGHT',      tr:'KURAKLIK',            grade:7, diff:3, unit:7 },
  { en:'BRING',        tr:'GETİRMEK',            grade:7, diff:2, unit:7 },
  { en:'LUCKY',        tr:'ŞANSLI',              grade:7, diff:1, unit:7 },
  { en:'UNLUCKY',      tr:'ŞANSSIZ',             grade:7, diff:1, unit:7 },
  { en:'CLIMATE',      tr:'İKLİM',               grade:7, diff:3, unit:7 },
  { en:'GRADUATE',     tr:'MEZUN OLMAK',          grade:7, diff:2, unit:7 },
  { en:'EDUCATION',    tr:'EĞİTİM',              grade:7, diff:3, unit:7 },
  { en:'HEALTH',       tr:'SAĞLIK',              grade:7, diff:2, unit:7 },
  { en:'DEFINITELY',   tr:'KESİNLİKLE',          grade:7, diff:3, unit:7 },
  { en:'COMPANY',      tr:'ŞİRKET',              grade:7, diff:3, unit:7 },
  { en:'ABROAD',       tr:'YURT DIŞI',            grade:7, diff:2, unit:7 },
  { en:'CURE DISEASE', tr:'HASTALIĞI İYİLEŞTİRMEK', grade:7, diff:3, unit:7 },
  { en:'SCIENTIST',    tr:'BİLİM İNSANI',         grade:7, diff:2, unit:7 },
  { en:'ENGINEER',     tr:'MÜHENDİS',            grade:7, diff:1, unit:7 },
  { en:'COMMUNICATION',tr:'İLETİŞİM',            grade:7, diff:3, unit:7 },
  { en:'EARTH',        tr:'DÜNYA',               grade:7, diff:1, unit:7 },
  { en:'RAPIDLY',      tr:'HIZLA',               grade:7, diff:3, unit:7 },
  { en:'HOPE',         tr:'UMUT',                grade:7, diff:2, unit:7 },
  { en:'INVENTION',    tr:'İCAT',                grade:7, diff:3, unit:7 },
  { en:'DISCOVER',     tr:'KEŞFETMEK',            grade:7, diff:2, unit:7 },
  { en:'ACHIEVE',      tr:'BAŞARMAK',             grade:7, diff:2, unit:7 },

  // ─── GRADE 7 UNIT 8 ──────────────────────────────────────────────────────────
  { en:'CITY HALL',    tr:'BELEDİYE BİNASI',     grade:7, diff:2, unit:8 },
  { en:'FIRE STATION', tr:'İTFAİYE İSTASYONU',   grade:7, diff:1, unit:8 },
  { en:'GREENGROCER',  tr:'MANAV',               grade:7, diff:2, unit:8 },
  { en:'TOY SHOP',     tr:'OYUNCAKÇI',           grade:7, diff:1, unit:8 },
  { en:'GOVERNORSHIP', tr:'VALİLİK',             grade:7, diff:3, unit:8 },
  { en:'MOVIE THEATER',tr:'SİNEMA',              grade:7, diff:1, unit:8 },
  { en:'SHOE SHOP',    tr:'AYAKKABICI',           grade:7, diff:1, unit:8 },
  { en:'MUNICIPALITY', tr:'BELEDİYE',            grade:7, diff:3, unit:8 },
  { en:'SHOPPING MALL',tr:'ALIŞVERİŞ MERKEZİ',   grade:7, diff:1, unit:8 },
  { en:'AIRPORT',      tr:'HAVALİMANI',           grade:7, diff:1, unit:8 },
  { en:'POLICE STATION',tr:'POLİS KARAKOLU',      grade:7, diff:1, unit:8 },
  { en:'POST OFFICE',  tr:'POSTANE',             grade:7, diff:1, unit:8 },
  { en:'COFFEE SHOP',  tr:'KAFE',                grade:7, diff:1, unit:8 },
  { en:'AMUSEMENT PARK',tr:'EĞLENCE PARKI',       grade:7, diff:2, unit:8 },
  { en:'HOSPITAL',     tr:'HASTANE',             grade:7, diff:1, unit:8 },
  { en:'NEWSAGENT',    tr:'GAZETE BAYİİ',         grade:7, diff:2, unit:8 },
  { en:'ART GALLERY',  tr:'SANAT GALERİSİ',       grade:7, diff:2, unit:8 },
  { en:'LIBRARY',      tr:'KÜTÜPhane',            grade:7, diff:1, unit:8 },
  { en:'BOOKSHOP',     tr:'KİTAPÇI',             grade:7, diff:1, unit:8 },
  { en:'BAKERY',       tr:'PASTANE / FIRIN',       grade:7, diff:1, unit:8 },
  { en:'ZOO',          tr:'HAYVANAT BAHÇESİ',     grade:7, diff:1, unit:8 },
  { en:'CONCERT HALL', tr:'KONSER SALONU',         grade:7, diff:2, unit:8 },
  { en:'PHARMACY',     tr:'ECZANE',              grade:7, diff:2, unit:8 },
  { en:'FLORIST',      tr:'ÇİÇEKÇİ',             grade:7, diff:2, unit:8 },
  { en:'GROCER',       tr:'BAKKAL',              grade:7, diff:2, unit:8 },
  { en:'DENTIST',      tr:'DİŞ HEKİMİ',          grade:7, diff:1, unit:8 },
  { en:'BUTCHER',      tr:'KASAP',               grade:7, diff:2, unit:8 },
  { en:'SOUVENIR',     tr:'HATIRA EŞYASI',        grade:7, diff:3, unit:8 },
  { en:'ATTRACTION',   tr:'TURİSTİK YER',         grade:7, diff:3, unit:8 },

  // ─── GRADE 7 UNIT 9 ──────────────────────────────────────────────────────────
  { en:'CLIMATE',      tr:'İKLİM',               grade:7, diff:2, unit:9 },
  { en:'ECO-FRIENDLY', tr:'ÇEVRE DOSTU',          grade:7, diff:2, unit:9 },
  { en:'EFFICIENT',    tr:'VERİMLİ',              grade:7, diff:3, unit:9 },
  { en:'OZONE LAYER',  tr:'OZON TABAKASI',        grade:7, diff:3, unit:9 },
  { en:'INCREASE',     tr:'ARTMAK',              grade:7, diff:2, unit:9 },
  { en:'POLLUTE',      tr:'KİRLETMEK',            grade:7, diff:2, unit:9 },
  { en:'RENEWABLE',    tr:'YENİLENEBİLİR',        grade:7, diff:3, unit:9 },
  { en:'RESPONSIBLE',  tr:'SORUMLU',             grade:7, diff:2, unit:9 },
  { en:'SOLAR ENERGY', tr:'GÜNEŞ ENERJİSİ',       grade:7, diff:1, unit:9 },
  { en:'WIND ENERGY',  tr:'RÜZGAR ENERJİSİ',      grade:7, diff:1, unit:9 },
  { en:'TAKE ACTION',  tr:'HAREKETE GEÇMEK',       grade:7, diff:2, unit:9 },
  { en:'TEMPERATURE',  tr:'SICAKLIK',             grade:7, diff:2, unit:9 },
  { en:'THREATEN',     tr:'TEHDİT ETMEK',          grade:7, diff:3, unit:9 },
  { en:'NATURE',       tr:'DOĞA',                grade:7, diff:1, unit:9 },
  { en:'GREENHOUSE',   tr:'SERA',                grade:7, diff:2, unit:9 },
  { en:'WASTE',        tr:'İSRAF ETMEK',           grade:7, diff:1, unit:9 },
  { en:'PROTECT',      tr:'KORUMAK',              grade:7, diff:1, unit:9 },
  { en:'RECYCLE',      tr:'GERİ DÖNÜŞTÜRMEK',     grade:7, diff:1, unit:9 },
  { en:'BALANCE',      tr:'DENGE',               grade:7, diff:2, unit:9 },
  { en:'UNPLUG',       tr:'FİŞİ ÇEKMEK',          grade:7, diff:2, unit:9 },
  { en:'DESTROY',      tr:'YOK ETMEK',            grade:7, diff:2, unit:9 },
  { en:'RUBBISH',      tr:'ÇÖP',                 grade:7, diff:1, unit:9 },
  { en:'GARBAGE',      tr:'ÇÖP',                 grade:7, diff:1, unit:9 },
  { en:'ENVIRONMENT',  tr:'ÇEVRE',               grade:7, diff:2, unit:9 },
  { en:'PESTICIDE',    tr:'BÖCEK İLACI',          grade:7, diff:3, unit:9 },
  { en:'REDUCE',       tr:'AZALTMAK',             grade:7, diff:2, unit:9 },
  { en:'REUSE',        tr:'YENİDEN KULLANMAK',    grade:7, diff:2, unit:9 },
  { en:'CAMPAIGN',     tr:'KAMPANYA',             grade:7, diff:3, unit:9 },
  { en:'CHEMICAL',     tr:'KİMYASAL',             grade:7, diff:3, unit:9 },
  { en:'HARMFUL',      tr:'ZARARLI',              grade:7, diff:2, unit:9 },
  { en:'PRECAUTION',   tr:'ÖNLEM',               grade:7, diff:3, unit:9 },
  { en:'PREVENT',      tr:'ÖNLEMEK',              grade:7, diff:2, unit:9 },
  { en:'NECESSARY',    tr:'GEREKLİ',             grade:7, diff:2, unit:9 },
  { en:'SAVE',         tr:'KURTARMAK',            grade:7, diff:1, unit:9 },
  { en:'DEFORESTATION',tr:'ORMANSIZLAŞMA',        grade:7, diff:3, unit:9 },

  // ─── GRADE 7 UNIT 10 ─────────────────────────────────────────────────────────
  { en:'MOON',         tr:'AY',                  grade:7, diff:1, unit:10 },
  { en:'RING',         tr:'HALKA',               grade:7, diff:2, unit:10 },
  { en:'ORBIT',        tr:'YÖRÜNGE',             grade:7, diff:3, unit:10 },
  { en:'PLANET',       tr:'GEZEGEN',             grade:7, diff:2, unit:10 },
  { en:'RESCUE',       tr:'KURTARMAK',            grade:7, diff:3, unit:10 },
  { en:'SHUTTLE',      tr:'UZAY MEKİĞİ',          grade:7, diff:2, unit:10 },
  { en:'UNIVERSE',     tr:'EVREN',               grade:7, diff:3, unit:10 },
  { en:'STAR',         tr:'YILDIZ',              grade:7, diff:1, unit:10 },
  { en:'COMET',        tr:'KUYRUKLU YILDIZ',      grade:7, diff:2, unit:10 },
  { en:'GIANT',        tr:'DEV',                 grade:7, diff:2, unit:10 },
  { en:'SATELLITE',    tr:'UYDU',                grade:7, diff:3, unit:10 },
  { en:'EVIDENCE',     tr:'KANIT',               grade:7, diff:3, unit:10 },
  { en:'EXPLORE',      tr:'KEŞFETMEK',            grade:7, diff:2, unit:10 },
  { en:'METEOR SHOWER',tr:'METEORİT YAĞMURU',    grade:7, diff:2, unit:10 },
  { en:'TEMPERATURE',  tr:'SICAKLIK',             grade:7, diff:2, unit:10 },
  { en:'OBSERVE',      tr:'GÖZLEMLEMEK',          grade:7, diff:2, unit:10 },
  { en:'DISCOVER',     tr:'KEŞFETMEK',            grade:7, diff:2, unit:10 },
  { en:'EXPERIMENT',   tr:'DENEY',               grade:7, diff:2, unit:10 },
  { en:'SPACE',        tr:'UZAY',                grade:7, diff:1, unit:10 },
  { en:'ASTEROID',     tr:'GÖKTAŞI',             grade:7, diff:2, unit:10 },
  { en:'SOLAR SYSTEM', tr:'GÜNEŞ SİSTEMİ',        grade:7, diff:1, unit:10 },
  { en:'TELESCOPE',    tr:'TELESKOP',             grade:7, diff:2, unit:10 },
  { en:'SURFACE',      tr:'YÜZEY',               grade:7, diff:2, unit:10 },
  { en:'EARTH',        tr:'DÜNYA',               grade:7, diff:1, unit:10 },
  { en:'PROOF',        tr:'KANIT',               grade:7, diff:2, unit:10 },
  { en:'GRAVITY',      tr:'YERÇEKİMİ',           grade:7, diff:2, unit:10 },
  { en:'MISSION',      tr:'GÖREV',               grade:7, diff:2, unit:10 },
  { en:'ALIEN',        tr:'UZAYLI',              grade:7, diff:1, unit:10 },
  { en:'FROZEN',       tr:'DONMUŞ',              grade:7, diff:1, unit:10 },
  { en:'DWARF',        tr:'CÜCE',                grade:7, diff:2, unit:10 },
  { en:'HABITABLE',    tr:'YAŞANILABİLİR',       grade:7, diff:3, unit:10 },
  { en:'VOYAGE',       tr:'YOLCULUK',            grade:7, diff:3, unit:10 },
  { en:'SPACECRAFT',   tr:'UZAY ARACI',           grade:7, diff:2, unit:10 },
  { en:'LAND',         tr:'İNMEK',               grade:7, diff:1, unit:10 },
  { en:'BRIGHT',       tr:'PARLAK',              grade:7, diff:1, unit:10 },
  { en:'CREATURE',     tr:'YARATIK',             grade:7, diff:2, unit:10 },
  { en:'FEWER',        tr:'DAHA AZ',             grade:7, diff:2, unit:10 },
  { en:'ROCKY',        tr:'KAYALIK',             grade:7, diff:1, unit:10 },
  { en:'CREW',         tr:'MÜRETTEBAT',           grade:7, diff:2, unit:10 },
  { en:'LIFE FORM',    tr:'YAŞAM FORMU',          grade:7, diff:2, unit:10 },
  { en:'LAUNCH',       tr:'FIRLATMAK',            grade:7, diff:2, unit:10 },

  // ─── GRADE 6 UNIT 1 ──────────────────────────────────────────────────────────
  { en:'LIFE',         tr:'HAYAT',               grade:6, diff:1, unit:1 },
  { en:'START',        tr:'BAŞLAMAK',            grade:6, diff:1, unit:1 },
  { en:'FINISH',       tr:'BİTİRMEK',            grade:6, diff:1, unit:1 },
  { en:'WEEKDAY',      tr:'HAFTA İÇİ',            grade:6, diff:2, unit:1 },
  { en:'WEEKEND',      tr:'HAFTA SONU',           grade:6, diff:1, unit:1 },
  { en:'TIME',         tr:'SAAT / ZAMAN',         grade:6, diff:1, unit:1 },
  { en:'DATE',         tr:'TARİH',               grade:6, diff:1, unit:1 },
  { en:'CLOCK',        tr:'SAAT',                grade:6, diff:1, unit:1 },
  { en:'ALWAYS',       tr:'HER ZAMAN',            grade:6, diff:1, unit:1 },
  { en:'USUALLY',      tr:'GENELLİKLE',           grade:6, diff:1, unit:1 },
  { en:'OFTEN',        tr:'SIKLIKLA',             grade:6, diff:1, unit:1 },
  { en:'SOMETIMES',    tr:'BAZEN',               grade:6, diff:1, unit:1 },
  { en:'SELDOM',       tr:'NADİREN',             grade:6, diff:3, unit:1 },
  { en:'RARELY',       tr:'NADİREN',             grade:6, diff:2, unit:1 },
  { en:'NEVER',        tr:'HİÇBİR ZAMAN',         grade:6, diff:1, unit:1 },
  { en:'EVERY DAY',    tr:'HER GÜN',             grade:6, diff:1, unit:1 },
  { en:'ONCE',         tr:'BİR KEZ',             grade:6, diff:1, unit:1 },
  { en:'TWICE',        tr:'İKİ KEZ',             grade:6, diff:1, unit:1 },
  { en:'HOW OFTEN',    tr:'NE SIKLIKTA',          grade:6, diff:2, unit:1 },
  { en:'MORNING',      tr:'SABAH',               grade:6, diff:1, unit:1 },
  { en:'AFTERNOON',    tr:'ÖĞLEDEN SONRA',        grade:6, diff:1, unit:1 },
  { en:'EVENING',      tr:'AKŞAM',               grade:6, diff:1, unit:1 },
  { en:'NIGHT',        tr:'GECE',                grade:6, diff:1, unit:1 },
  { en:'QUARTER PAST', tr:'ÇEYREĞİ GEÇİYOR',     grade:6, diff:2, unit:1 },
  { en:'HALF PAST',    tr:'BUÇUK',               grade:6, diff:2, unit:1 },
  { en:'O CLOCK',      tr:'TAM (SAAT)',           grade:6, diff:2, unit:1 },
  { en:'BREAKFAST',    tr:'KAHVALTI',             grade:6, diff:1, unit:1 },
  { en:'LUNCH',        tr:'ÖĞLE YEMEĞİ',          grade:6, diff:1, unit:1 },
  { en:'DINNER',       tr:'AKŞAM YEMEĞİ',         grade:6, diff:1, unit:1 },
  { en:'WAKE UP',      tr:'UYANMAK',             grade:6, diff:1, unit:1 },
  { en:'WASH FACE',    tr:'YÜZÜNÜ YIKAMAK',       grade:6, diff:1, unit:1 },
  { en:'BRUSH TEETH',  tr:'DİŞ FIRCALAMAK',       grade:6, diff:1, unit:1 },
  { en:'GET DRESSED',  tr:'GİYİNMEK',             grade:6, diff:1, unit:1 },
  { en:'ARRIVE SCHOOL',tr:'OKULA VARMAK',          grade:6, diff:2, unit:1 },
  { en:'STUDY LESSON', tr:'DERS ÇALIŞMAK',         grade:6, diff:1, unit:1 },
  { en:'DO HOMEWORK',  tr:'ÖDEV YAPMAK',           grade:6, diff:1, unit:1 },
  { en:'COME BACK HOME',tr:'EVE DÖNMEK',           grade:6, diff:2, unit:1 },
  { en:'GO TO GYM',    tr:'SPOR SALONUNA GİTMEK', grade:6, diff:2, unit:1 },
  { en:'READ BOOK',    tr:'KİTAP OKUMAK',          grade:6, diff:1, unit:1 },
  { en:'WATCH TV',     tr:'TV İZLEMEK',            grade:6, diff:1, unit:1 },
  { en:'GO ONLINE',    tr:'İNTERNETE GİRMEK',      grade:6, diff:1, unit:1 },
  { en:'PLAY GAMES',   tr:'OYUN OYNAMAK',          grade:6, diff:1, unit:1 },
  { en:'TAKE SHOWER',  tr:'DUŞ ALMAK',             grade:6, diff:1, unit:1 },
  { en:'HAVE BATH',    tr:'BANYO YAPMAK',           grade:6, diff:1, unit:1 },
  { en:'HAVE A REST',  tr:'DİNLENMEK',             grade:6, diff:1, unit:1 },
  { en:'TAKE A NAP',   tr:'KESTIRMEK',             grade:6, diff:2, unit:1 },
  { en:'MEET FRIENDS', tr:'ARKADAŞLARLA BULUŞMAK', grade:6, diff:1, unit:1 },
  { en:'GO SHOPPING',  tr:'ALIŞVERİŞE GİTMEK',    grade:6, diff:1, unit:1 },
  { en:'ATTEND COURSE',tr:'KURSA GİTMEK',           grade:6, diff:2, unit:1 },

  // ─── GRADE 6 UNIT 2 ──────────────────────────────────────────────────────────
  { en:'BAGEL',        tr:'SİMİT',               grade:6, diff:2, unit:2 },
  { en:'BUTTER',       tr:'TEREYAĞI',            grade:6, diff:1, unit:2 },
  { en:'CEREAL',       tr:'TAHIL GEVREĞİ',        grade:6, diff:1, unit:2 },
  { en:'CROISSANT',    tr:'KROİSAN',             grade:6, diff:2, unit:2 },
  { en:'EGG',          tr:'YUMURTA',             grade:6, diff:1, unit:2 },
  { en:'FRUIT JUICE',  tr:'MEYVE SUYU',           grade:6, diff:1, unit:2 },
  { en:'JAM',          tr:'REÇEL',               grade:6, diff:1, unit:2 },
  { en:'OMELETTE',     tr:'OMLET',               grade:6, diff:2, unit:2 },
  { en:'MUFFIN',       tr:'MAFİN',               grade:6, diff:1, unit:2 },
  { en:'PANCAKE',      tr:'KREP',                grade:6, diff:1, unit:2 },
  { en:'SAUSAGE',      tr:'SOSİS',               grade:6, diff:1, unit:2 },
  { en:'NUTRITIOUS',   tr:'BESLEYİCİ',           grade:6, diff:3, unit:2 },
  { en:'TEA',          tr:'ÇAY',                 grade:6, diff:1, unit:2 },
  { en:'COFFEE',       tr:'KAHVE',               grade:6, diff:1, unit:2 },
  { en:'MILK',         tr:'SÜT',                 grade:6, diff:1, unit:2 },
  { en:'TOMATO',       tr:'DOMATES',             grade:6, diff:1, unit:2 },
  { en:'POTATO',       tr:'PATATES',             grade:6, diff:1, unit:2 },
  { en:'CHEESE',       tr:'PEYNİR',              grade:6, diff:1, unit:2 },
  { en:'SALAMI',       tr:'SALAM',               grade:6, diff:2, unit:2 },
  { en:'CUCUMBER',     tr:'SALATALIK',            grade:6, diff:1, unit:2 },
  { en:'HONEY',        tr:'BAL',                 grade:6, diff:1, unit:2 },
  { en:'BREAD',        tr:'EKMEK',               grade:6, diff:1, unit:2 },
  { en:'GARLIC',       tr:'SARIMSAK',            grade:6, diff:2, unit:2 },
  { en:'BEANS',        tr:'FASULYE',             grade:6, diff:1, unit:2 },
  { en:'VEGETABLE',    tr:'SEBZE',               grade:6, diff:1, unit:2 },
  { en:'ONION',        tr:'SOĞAN',               grade:6, diff:1, unit:2 },
  { en:'FRESH FRUIT',  tr:'TAZE MEYVE',           grade:6, diff:1, unit:2 },
  { en:'OLIVES',       tr:'ZEYTİN',              grade:6, diff:1, unit:2 },
  { en:'SUGAR',        tr:'ŞEKER',               grade:6, diff:1, unit:2 },
  { en:'SALT',         tr:'TUZ',                 grade:6, diff:1, unit:2 },
  { en:'BAKED',        tr:'FIRINLANMIŞ',          grade:6, diff:2, unit:2 },
  { en:'FRIED',        tr:'KIZARTILMIŞ',          grade:6, diff:1, unit:2 },
  { en:'GRILLED',      tr:'IZGARADA PİŞİRİLMİŞ', grade:6, diff:2, unit:2 },
  { en:'BOILED',       tr:'HAŞLANMIŞ',            grade:6, diff:2, unit:2 },
  { en:'OAT',          tr:'YULAF',               grade:6, diff:2, unit:2 },
  { en:'DELICIOUS',    tr:'LEZZETLİ',             grade:6, diff:1, unit:2 },
  { en:'PREFER',       tr:'TERCİH ETMEK',         grade:6, diff:2, unit:2 },
  { en:'ENJOY',        tr:'ZEVK ALMAK',            grade:6, diff:1, unit:2 },
  { en:'COOK',         tr:'PİŞİRMEK',             grade:6, diff:1, unit:2 },
  { en:'BUY',          tr:'SATIN ALMAK',           grade:6, diff:1, unit:2 },
  { en:'TASTE',        tr:'TAT',                 grade:6, diff:1, unit:2 },
  { en:'PREPARE',      tr:'HAZIRLAMAK',           grade:6, diff:2, unit:2 },
  { en:'HUNGRY',       tr:'AÇ',                  grade:6, diff:1, unit:2 },
  { en:'THIRSTY',      tr:'SUSUZ',               grade:6, diff:1, unit:2 },
  { en:'TRADITIONAL',  tr:'GELENEKSEL',           grade:6, diff:3, unit:2 },
  { en:'HEALTHY',      tr:'SAĞLIKLI',             grade:6, diff:1, unit:2 },
  { en:'UNHEALTHY',    tr:'SAĞLIKSIZ',            grade:6, diff:2, unit:2 },
  { en:'JUNK FOOD',    tr:'ABUR CUBUR',           grade:6, diff:1, unit:2 },
  { en:'SNACK',        tr:'ATİŞTİRMELİK',         grade:6, diff:1, unit:2 },
  { en:'MEAL',         tr:'ÖĞÜN',                grade:6, diff:1, unit:2 },

  // ─── GRADE 6 UNIT 3 ──────────────────────────────────────────────────────────
  { en:'CROWDED',      tr:'KALABALİK',            grade:6, diff:3, unit:3 },
  { en:'BUSY',         tr:'MEŞGUL',              grade:6, diff:1, unit:3 },
  { en:'DOWNTOWN',     tr:'ŞEHİR MERKEZİ',        grade:6, diff:2, unit:3 },
  { en:'TRAFFIC JAM',  tr:'TRAFİK TIKANIKLIĞI',   grade:6, diff:1, unit:3 },
  { en:'HOMETOWN',     tr:'MEMLEKET',             grade:6, diff:2, unit:3 },
  { en:'KIOSK',        tr:'BÜFE',                grade:6, diff:3, unit:3 },
  { en:'COMPARE',      tr:'KARŞILAŞTIRMAK',       grade:6, diff:3, unit:3 },
  { en:'SELL',         tr:'SATMAK',              grade:6, diff:1, unit:3 },
  { en:'SKYSCRAPER',   tr:'GÖKDELEn',            grade:6, diff:2, unit:3 },
  { en:'STREET',       tr:'SOKAK',               grade:6, diff:1, unit:3 },
  { en:'VILLAGE',      tr:'KÖY',                 grade:6, diff:2, unit:3 },
  { en:'TOWN',         tr:'KASABA',              grade:6, diff:1, unit:3 },
  { en:'CITY',         tr:'ŞEHİR',               grade:6, diff:1, unit:3 },
  { en:'FEED',         tr:'BESLEMEK',             grade:6, diff:1, unit:3 },
  { en:'FARM',         tr:'ÇİFTLİK',             grade:6, diff:1, unit:3 },
  { en:'FLAT',         tr:'DAİRE',               grade:6, diff:3, unit:3 },
  { en:'NOW',          tr:'ŞİMDİ',               grade:6, diff:1, unit:3 },
  { en:'RIGHT NOW',    tr:'ŞU AN',               grade:6, diff:3, unit:3 },
  { en:'AT THE MOMENT',tr:'ŞU ANDA',             grade:6, diff:3, unit:3 },
  { en:'NEIGHBORHOOD', tr:'MAHALLE',              grade:6, diff:3, unit:3 },
  { en:'BETTER',       tr:'DAHA İYİ',             grade:6, diff:2, unit:3 },
  { en:'WORSE',        tr:'DAHA KÖTÜ',            grade:6, diff:2, unit:3 },
  { en:'ENJOYABLE',    tr:'EĞLENCELİ',            grade:6, diff:2, unit:3 },
  { en:'RELAXING',     tr:'DİNLENDİRİCİ',         grade:6, diff:2, unit:3 },
  { en:'QUEUE',        tr:'KUYRUK',              grade:6, diff:3, unit:3 },
  { en:'LINE',         tr:'SIRA',                grade:6, diff:3, unit:3 },
  { en:'SQUARE',       tr:'MEYDAN',              grade:6, diff:3, unit:3 },
  { en:'BUILDING',     tr:'BİNA',                grade:6, diff:3, unit:3 },
  { en:'PLAYGROUND',   tr:'OYUN PARKI',           grade:6, diff:2, unit:3 },
  { en:'COMFORTABLE',  tr:'RAHAT',               grade:6, diff:2, unit:3 },
  { en:'CROSS',        tr:'KARŞIYA GEÇMEK',       grade:6, diff:2, unit:3 },
  { en:'POPULATION',   tr:'NÜFUS',               grade:6, diff:3, unit:3 },
  { en:'RENT',         tr:'KİRA',                grade:6, diff:2, unit:3 },
  { en:'WAIT',         tr:'BEKLEMEK',             grade:6, diff:2, unit:3 },
  { en:'PREPARE',      tr:'HAZIRLAMAK',           grade:6, diff:3, unit:3 },
  { en:'COUNTRY LIFE', tr:'KIRSAL HAYAT',          grade:6, diff:3, unit:3 },
  { en:'BEAUTIFUL',    tr:'GÜZEL',               grade:6, diff:1, unit:3 },
  { en:'UGLY',         tr:'ÇİRKİN',              grade:6, diff:1, unit:3 },
  { en:'TALL',         tr:'UZUN',                grade:6, diff:1, unit:3 },
  { en:'LONG',         tr:'UZUN',                grade:6, diff:1, unit:3 },
  { en:'SHORT',        tr:'KISA',                grade:6, diff:1, unit:3 },
  { en:'HIGH',         tr:'YÜKSEK',              grade:6, diff:2, unit:3 },
  { en:'LOW',          tr:'ALÇAK',               grade:6, diff:2, unit:3 },
  { en:'CLEAN',        tr:'TEMİZ',               grade:6, diff:1, unit:3 },
  { en:'DIRTY',        tr:'KİRLİ',               grade:6, diff:1, unit:3 },
  { en:'EXPENSIVE',    tr:'PAHALI',              grade:6, diff:3, unit:3 },
  { en:'CHEAP',        tr:'UCUZ',                grade:6, diff:2, unit:3 },
  { en:'BIG',          tr:'BÜYÜK',               grade:6, diff:1, unit:3 },
  { en:'LARGE',        tr:'BÜYÜK',               grade:6, diff:2, unit:3 },
  { en:'SMALL',        tr:'KÜÇÜK',               grade:6, diff:1, unit:3 },
  { en:'NOISY',        tr:'GÜRÜLTÜLÜ',            grade:6, diff:2, unit:3 },
  { en:'QUIET',        tr:'SAKİN',               grade:6, diff:2, unit:3 },
  { en:'DANGEROUS',    tr:'TEHLİKELİ',            grade:6, diff:3, unit:3 },
  { en:'SAFE',         tr:'GÜVENLİ',             grade:6, diff:2, unit:3 },
  { en:'GOOD',         tr:'İYİ',                 grade:6, diff:1, unit:3 },
  { en:'BAD',          tr:'KÖTÜ',                grade:6, diff:1, unit:3 },
  { en:'EXCITING',     tr:'HEYECAN VERİCİ',       grade:6, diff:2, unit:3 },
  { en:'BORING',       tr:'SIKI',                grade:6, diff:1, unit:3 },

  // ─── GRADE 6 UNIT 7 ──────────────────────────────────────────────────────────
  { en:'SAILING',      tr:'YELKEN',              grade:6, diff:2, unit:7 },
  { en:'SKIING',       tr:'KAYAK',               grade:6, diff:1, unit:7 },
  { en:'TENT',         tr:'ÇADIR',               grade:6, diff:1, unit:7 },
  { en:'CAMPING',      tr:'KAMP YAPMA',           grade:6, diff:1, unit:7 },
  { en:'RAFTING',      tr:'RAFTİNG',             grade:6, diff:2, unit:7 },
  { en:'SANDCASTLE',   tr:'KUM KALESİ',           grade:6, diff:3, unit:7 },
  { en:'SCUBA DIVING', tr:'TÜPLÜ DALMA',          grade:6, diff:1, unit:7 },
  { en:'PARAGLIDING',  tr:'YAMAÇ PARAŞÜTÇÜLÜĞü', grade:6, diff:2, unit:7 },
  { en:'HIKING',       tr:'DOĞA YÜRÜYÜŞÜ',        grade:6, diff:1, unit:7 },
  { en:'SIGHTSEEING',  tr:'TURİSTİK GEZİ',        grade:6, diff:3, unit:7 },
  { en:'FOREST',       tr:'ORMAN',               grade:6, diff:1, unit:7 },
  { en:'FLOWER',       tr:'ÇİÇEK',               grade:6, diff:2, unit:7 },
  { en:'LAKE',         tr:'GÖL',                 grade:6, diff:2, unit:7 },
  { en:'RIVER',        tr:'NEHİR',               grade:6, diff:2, unit:7 },
  { en:'MOUNTAIN',     tr:'DAĞ',                 grade:6, diff:2, unit:7 },
  { en:'BEACH',        tr:'PLAJ',                grade:6, diff:1, unit:7 },
  { en:'SEASIDE',      tr:'SAHİL',               grade:6, diff:2, unit:7 },
  { en:'PICK FRUIT',   tr:'MEYVE TOPLAMAK',       grade:6, diff:1, unit:7 },

  // ─── GRADE 6 UNIT 8 ──────────────────────────────────────────────────────────
  { en:'AUTHOR',       tr:'YAZAR',               grade:6, diff:2, unit:8 },
  { en:'BORROW',       tr:'ÖDÜNÇ ALMAK',          grade:6, diff:3, unit:8 },
  { en:'LEND',         tr:'ÖDÜNÇ VERMEK',         grade:6, diff:3, unit:8 },
  { en:'BOOK SHELF',   tr:'KİTAP RAFI',           grade:6, diff:1, unit:8 },
  { en:'DICTIONARY',   tr:'SÖZLÜK',              grade:6, diff:3, unit:8 },
  { en:'LIBRARY',      tr:'KÜTÜPHANE',            grade:6, diff:1, unit:8 },
  { en:'MAGAZINE',     tr:'DERGİ',               grade:6, diff:2, unit:8 },
  { en:'POETRY',       tr:'ŞİİR',                grade:6, diff:3, unit:8 },
  { en:'NEWSPAPER',    tr:'GAZETE',              grade:6, diff:1, unit:8 },
  { en:'NOVEL',        tr:'ROMAN',               grade:6, diff:2, unit:8 },
  { en:'OPPOSITE',     tr:'KARŞISINDA',           grade:6, diff:3, unit:8 },
  { en:'BEHIND',       tr:'ARKASINDA',            grade:6, diff:1, unit:8 },
  { en:'BETWEEN',      tr:'ARASINDA',             grade:6, diff:2, unit:8 },
  { en:'NEXT TO',      tr:'YANINDA',             grade:6, diff:2, unit:8 },
  { en:'UNDER',        tr:'ALTINDA',             grade:6, diff:1, unit:8 },
  { en:'OVER',         tr:'ÜSTÜNDE',             grade:6, diff:2, unit:8 },

  // ─── GRADE 8 UNIT 1 ──────────────────────────────────────────────────────────
  { en:'BACK UP',      tr:'DESTEKLEMEK',          grade:8, diff:2, unit:1 },
  { en:'BUDDY',        tr:'YAKIN ARKADAŞ',        grade:8, diff:1, unit:1 },
  { en:'COOL',         tr:'HAVALİ',              grade:8, diff:1, unit:1 },
  { en:'GET ON WELL',  tr:'İYİ GEÇİNMEK',         grade:8, diff:2, unit:1 },
  { en:'RELY ON',      tr:'GÜVENİP DAYANMAK',     grade:8, diff:2, unit:1 },
  { en:'COUNT ON',     tr:'GÜVENMEK',             grade:8, diff:2, unit:1 },
  { en:'BEST FRIEND',  tr:'EN İYİ ARKADAŞ',       grade:8, diff:1, unit:1 },
  { en:'CLOSE FRIEND', tr:'YAKIN ARKADAŞ',        grade:8, diff:1, unit:1 },
  { en:'TRUE FRIEND',  tr:'GERÇEK ARKADAŞ',       grade:8, diff:1, unit:1 },
  { en:'LAID BACK',    tr:'SAKİN / RAHAT',        grade:8, diff:2, unit:1 },
  { en:'KEEP SECRET',  tr:'SIR SAKLAMAK',          grade:8, diff:2, unit:1 },
  { en:'SHARE',        tr:'PAYLAŞMAK',            grade:8, diff:1, unit:1 },
  { en:'INVITE',       tr:'DAVET ETMEK',           grade:8, diff:1, unit:1 },
  { en:'ACCEPT',       tr:'KABUL ETMEK',           grade:8, diff:1, unit:1 },
  { en:'REFUSE',       tr:'REDDETMEK',            grade:8, diff:1, unit:1 },
  { en:'MAKE AN EXCUSE',tr:'BAHANE ÜRETMEK',       grade:8, diff:2, unit:1 },
  { en:'APOLOGIZE',    tr:'ÖZÜR DİLEMEK',          grade:8, diff:2, unit:1 },
  { en:'FRIENDSHIP',   tr:'ARKADAŞLIK',            grade:8, diff:1, unit:1 },
  { en:'TELL TRUTH',   tr:'DOĞRUYU SÖYLEMEK',      grade:8, diff:1, unit:1 },
  { en:'TELL LIES',    tr:'YALAN SÖYLEMEK',        grade:8, diff:1, unit:1 },
  { en:'JOIN',         tr:'KATILMAK',             grade:8, diff:1, unit:1 },
  { en:'ADVENTUROUS',  tr:'MACERAci',             grade:8, diff:3, unit:1 },
  { en:'AMUSING',      tr:'EĞLENCELİ',            grade:8, diff:2, unit:1 },
  { en:'AWESOME',      tr:'MUHTEŞEM',             grade:8, diff:1, unit:1 },
  { en:'ARROGANT',     tr:'KİBİRLİ',              grade:8, diff:3, unit:1 },
  { en:'CARING',       tr:'SEVECen',              grade:8, diff:2, unit:1 },
  { en:'DEADLINE',     tr:'SON TARİH',             grade:8, diff:2, unit:1 },
  { en:'BUSY',         tr:'MEŞGUL',              grade:8, diff:1, unit:1 },
  { en:'COME OVER',    tr:'UĞRAMAK',              grade:8, diff:1, unit:1 },
  { en:'EVENT',        tr:'ETKİNLİK',             grade:8, diff:1, unit:1 },
  { en:'EXHIBITION',   tr:'SERGİ',               grade:8, diff:3, unit:1 },
  { en:'SENDER',       tr:'GÖNDEREN',             grade:8, diff:2, unit:1 },
  { en:'RECEIVER',     tr:'ALAN KİŞİ',            grade:8, diff:2, unit:1 },
  { en:'RESPONSE',     tr:'CEVAP / TEPKİ',        grade:8, diff:2, unit:1 },
  { en:'GENEROUS',     tr:'CÖMERT',              grade:8, diff:2, unit:1 },
  { en:'HONEST',       tr:'DÜRÜST',              grade:8, diff:1, unit:1 },
  { en:'JEALOUS',      tr:'KISKANÇI',             grade:8, diff:2, unit:1 },
  { en:'MEAN',         tr:'KÖTÜ KALPLİ',          grade:8, diff:1, unit:1 },
  { en:'POLITE',       tr:'NAZIK',               grade:8, diff:2, unit:1 },
  { en:'RELATIONSHIP', tr:'İLİŞKİ',              grade:8, diff:3, unit:1 },
  { en:'STUBBORN',     tr:'İNATÇI',              grade:8, diff:3, unit:1 },
  { en:'SNEAKY',       tr:'KURNAZ',              grade:8, diff:2, unit:1 },
  { en:'SLUMBER',      tr:'GECELEME',             grade:8, diff:3, unit:1 },
  { en:'INVITATION',   tr:'DAVET',               grade:8, diff:2, unit:1 },
  { en:'INFORM',       tr:'BİLGİLENDİRMEK',       grade:8, diff:2, unit:1 },
  { en:'EXPECT',       tr:'BEKLEMEK',             grade:8, diff:2, unit:1 },
  { en:'DETERMINED',   tr:'KARARLI',              grade:8, diff:3, unit:1 },
  { en:'CELEBRATE',    tr:'KUTLAMAK',             grade:8, diff:1, unit:1 },
  { en:'CUSTOMER',     tr:'MÜŞTERİ',             grade:8, diff:2, unit:1 },
  { en:'ARGUE',        tr:'TARTIŞMAK',            grade:8, diff:2, unit:1 },
  { en:'TACTFUL',      tr:'DİPLOMATİK',           grade:8, diff:3, unit:1 },
  { en:'TOGETHER',     tr:'BİRLİKTE',             grade:8, diff:1, unit:1 },
  { en:'UNTIL',        tr:'KADAR',               grade:8, diff:2, unit:1 },
  { en:'UNRELIABLE',   tr:'GÜVENİLMEZ',           grade:8, diff:3, unit:1 },
  { en:'DECIDE',       tr:'KARAR VERMEK',          grade:8, diff:1, unit:1 },
  { en:'DEPEND ON',    tr:'BAĞIMLI OLMAK',         grade:8, diff:2, unit:1 },
  { en:'TRUST',        tr:'GÜVENMEK',             grade:8, diff:2, unit:1 },
  { en:'RELAXED',      tr:'RAHAT',               grade:8, diff:2, unit:1 },

  // ─── GRADE 8 UNIT 2 ──────────────────────────────────────────────────────────
  { en:'MUSIC BAND',   tr:'MÜZİK GRUBU',          grade:8, diff:1, unit:2 },
  { en:'CASUAL',       tr:'GÜNLÜK GİYİM',          grade:8, diff:2, unit:2 },
  { en:'FASHIONABLE',  tr:'MODALİ',              grade:8, diff:1, unit:2 },
  { en:'IMPRESSIVE',   tr:'ETKİLEYİCİ',           grade:8, diff:2, unit:2 },
  { en:'UNBEARABLE',   tr:'DAYANILMAZ',           grade:8, diff:3, unit:2 },
  { en:'TRENDY',       tr:'MODA',                grade:8, diff:2, unit:2 },
  { en:'TERRIBLE',     tr:'KORKUNÇ',             grade:8, diff:1, unit:2 },
  { en:'RIDICULOUS',   tr:'SAÇMA',               grade:8, diff:3, unit:2 },
  { en:'SERIOUS',      tr:'CİDDİ',               grade:8, diff:2, unit:2 },
  { en:'SNOB',         tr:'SNOB',                grade:8, diff:2, unit:2 },
  { en:'TEENAGER',     tr:'GENÇ',                grade:8, diff:1, unit:2 },
  { en:'TERRIFIC',     tr:'HARIKA',              grade:8, diff:2, unit:2 },
  { en:'AWESOME',      tr:'MUHTEŞEM',             grade:8, diff:2, unit:2 },
  { en:'FORMAL OUTFIT',tr:'RESMİ KIYAFEt',        grade:8, diff:2, unit:2 },
  { en:'NERD',         tr:'KİTAP KURDU',          grade:8, diff:1, unit:2 },
  { en:'EXHIBITION',   tr:'SERGİ',               grade:8, diff:3, unit:2 },
  { en:'INTERESTED IN',tr:'İLGİLENMEK',           grade:8, diff:1, unit:2 },
  { en:'FOND OF',      tr:'SEVMEK',              grade:8, diff:2, unit:2 },
  { en:'KEEN ON',      tr:'HEVESLİ OLMAK',        grade:8, diff:2, unit:2 },
  { en:'ENJOY',        tr:'ZEVK ALMAK',            grade:8, diff:1, unit:2 },
  { en:'WONDERFUL',    tr:'HARIKA',              grade:8, diff:1, unit:2 },
  { en:'FASCINATING',  tr:'BÜYÜLEYİCİ',          grade:8, diff:3, unit:2 },
  { en:'AMAZING',      tr:'İNANILMAZ',            grade:8, diff:1, unit:2 },
  { en:'STYLISH',      tr:'ŞIK',                 grade:8, diff:2, unit:2 },
  { en:'FREE TIME',    tr:'BOŞ ZAMAN',            grade:8, diff:1, unit:2 },
  { en:'NEVER',        tr:'HİÇBİR ZAMAN',         grade:8, diff:1, unit:2 },
  { en:'PREFER',       tr:'TERCİH ETMEK',         grade:8, diff:2, unit:2 },
  { en:'ALWAYS',       tr:'HER ZAMAN',            grade:8, diff:1, unit:2 },
  { en:'OFTEN',        tr:'SIKLIKLA',             grade:8, diff:1, unit:2 },
  { en:'USUALLY',      tr:'GENELLİKLE',           grade:8, diff:1, unit:2 },
  { en:'SOMETIMES',    tr:'BAZEN',               grade:8, diff:1, unit:2 },
  { en:'SELDOM',       tr:'NADİREN',             grade:8, diff:3, unit:2 },
  { en:'RARELY',       tr:'NADİREN',             grade:8, diff:3, unit:2 },
  { en:'HARDLY EVER',  tr:'NEREDEYSE HİÇ',        grade:8, diff:2, unit:2 },
  { en:'ONCE',         tr:'BİR KEZ',             grade:8, diff:1, unit:2 },
  { en:'TWICE',        tr:'İKİ KEZ',             grade:8, diff:1, unit:2 },

  // ─── GRADE 8 UNIT 3 ──────────────────────────────────────────────────────────
  { en:'BAKE',         tr:'FINDA PİŞİRMEK',       grade:8, diff:1, unit:3 },
  { en:'CHOP',         tr:'DOĞRAMAK',             grade:8, diff:2, unit:3 },
  { en:'KNIFE',        tr:'BÇAK',                grade:8, diff:1, unit:3 },
  { en:'FRY',          tr:'KIZARTMAK',            grade:8, diff:1, unit:3 },
  { en:'MIX',          tr:'KARISTIRMAK',          grade:8, diff:1, unit:3 },
  { en:'TEASPOON',     tr:'ÇAY KAŞIĞI',           grade:8, diff:2, unit:3 },
  { en:'BOIL',         tr:'KAYNATMAK',            grade:8, diff:1, unit:3 },
  { en:'PEEL',         tr:'SOYMAK',              grade:8, diff:2, unit:3 },
  { en:'TABLESPOON',   tr:'YEMEK KAŞIĞI',         grade:8, diff:2, unit:3 },
  { en:'HEAT',         tr:'ISITMAK',              grade:8, diff:1, unit:3 },
  { en:'POUR',         tr:'DÖKMEK',              grade:8, diff:2, unit:3 },
  { en:'FORK',         tr:'ÇATAL',               grade:8, diff:2, unit:3 },
  { en:'GRILL',        tr:'IZGARA YAPMAK',        grade:8, diff:1, unit:3 },
  { en:'SLICE',        tr:'DİLİMLEMEK',           grade:8, diff:2, unit:3 },
  { en:'PAN',          tr:'TAVA',                grade:8, diff:1, unit:3 },
  { en:'STEAM',        tr:'BUHARDA PİŞİRMEK',     grade:8, diff:3, unit:3 },
  { en:'DICE',         tr:'KÜÇÜK KUPLER KES',      grade:8, diff:2, unit:3 },
  { en:'PLATE',        tr:'TABAK',               grade:8, diff:2, unit:3 },
  { en:'ROAST',        tr:'FIRINDA KAVURMAK',      grade:8, diff:3, unit:3 },
  { en:'MASH',         tr:'EZMEK',               grade:8, diff:2, unit:3 },
  { en:'OVEN',         tr:'FIRIN',               grade:8, diff:1, unit:3 },
  { en:'ADD',          tr:'EKLEMEK',              grade:8, diff:1, unit:3 },
  { en:'CUP',          tr:'BARDAK',              grade:8, diff:1, unit:3 },
  { en:'STIR',         tr:'KARISTIRMAK',          grade:8, diff:2, unit:3 },
  { en:'BOWL',         tr:'KASE',                grade:8, diff:2, unit:3 },
  { en:'SPREAD',       tr:'SÜRMEK',              grade:8, diff:3, unit:3 },
  { en:'SAUCEPAN',     tr:'TENCERE',             grade:8, diff:2, unit:3 },
  { en:'GRATER',       tr:'RENDE',               grade:8, diff:3, unit:3 },
  { en:'STRAINER',     tr:'SÜZGEÇ',              grade:8, diff:3, unit:3 },
  { en:'BAKING TRAY',  tr:'FIRIN TEPSİSİ',        grade:8, diff:2, unit:3 },
  { en:'FLOUR',        tr:'UN',                  grade:8, diff:2, unit:3 },
  { en:'BITTER',       tr:'ACI',                 grade:8, diff:2, unit:3 },
  { en:'FIRST',        tr:'İLK',                 grade:8, diff:2, unit:3 },
  { en:'MEAT',         tr:'ET',                  grade:8, diff:1, unit:3 },
  { en:'SALTY',        tr:'TUZLU',               grade:8, diff:1, unit:3 },
  { en:'SECOND',       tr:'İKİNCİ',              grade:8, diff:2, unit:3 },
  { en:'BAKING POWDER',tr:'KABARTMA TOZU',        grade:8, diff:3, unit:3 },
  { en:'SOUR',         tr:'EKŞİ',                grade:8, diff:1, unit:3 },
  { en:'NEXT',         tr:'SONRA / SONRAKİ',      grade:8, diff:2, unit:3 },
  { en:'PEPPER',       tr:'BİBER',               grade:8, diff:1, unit:3 },
  { en:'SPICY',        tr:'BAHARLI',             grade:8, diff:2, unit:3 },
  { en:'THEN',         tr:'SONRA',               grade:8, diff:1, unit:3 },
  { en:'CUCUMBER',     tr:'SALATALIK',            grade:8, diff:2, unit:3 },
  { en:'SWEET',        tr:'TATLI',               grade:8, diff:1, unit:3 },
  { en:'TASTY',        tr:'LEZZETLİ',             grade:8, diff:1, unit:3 },
  { en:'AFTER THAT',   tr:'ONDAN SONRA',          grade:8, diff:2, unit:3 },
  { en:'ONION',        tr:'SOĞAN',               grade:8, diff:1, unit:3 },
  { en:'MILKY',        tr:'SÜTLÜ',               grade:8, diff:2, unit:3 },
  { en:'FINALLY',      tr:'SONUNDA',             grade:8, diff:2, unit:3 },
  { en:'RICE',         tr:'PİRİNÇ',              grade:8, diff:1, unit:3 },
  { en:'GREASY',       tr:'YAĞLI',               grade:8, diff:2, unit:3 },
  { en:'OILY',         tr:'YAĞLI',               grade:8, diff:2, unit:3 },
  { en:'AFTER',        tr:'SONRA',               grade:8, diff:1, unit:3 },
  { en:'SEAWEED',      tr:'DENİZ YOSUNU',         grade:8, diff:3, unit:3 },
  { en:'BEFORE',       tr:'ÖNCE',                grade:8, diff:2, unit:3 },
  { en:'GINGER',       tr:'ZENCEFİL',             grade:8, diff:3, unit:3 },
  { en:'GARLIC',       tr:'SARIMSAK',            grade:8, diff:1, unit:3 },
  { en:'INGREDIENT',   tr:'MALZEME',             grade:8, diff:3, unit:3 },
  { en:'RECIPE',       tr:'TARİF',               grade:8, diff:3, unit:3 },
  { en:'HEALTHY',      tr:'SAĞLIKLI',             grade:8, diff:2, unit:3 },
  { en:'UNHEALTHY',    tr:'SAĞLIKSIZ',            grade:8, diff:3, unit:3 },
  { en:'SERVE',        tr:'SERVİS YAPMAK',        grade:8, diff:1, unit:3 },
  { en:'REFRIGERATOR', tr:'BUZDOLABI',            grade:8, diff:3, unit:3 },
  { en:'FRIDGE',       tr:'BUZDOLABI',            grade:8, diff:2, unit:3 },
  { en:'YEAST',        tr:'MAYA',                grade:8, diff:3, unit:3 },
  { en:'FREEZER',      tr:'DERİN DONDURUCU',      grade:8, diff:2, unit:3 },
  { en:'DISH',         tr:'YEMEK',               grade:8, diff:1, unit:3 },
  { en:'SPRINKLE',     tr:'SERPMEK',              grade:8, diff:3, unit:3 },
  { en:'WRAP',         tr:'SARMAK',              grade:8, diff:3, unit:3 },
  { en:'SQUEEZE',      tr:'SIKMAK',              grade:8, diff:3, unit:3 },
  { en:'PASTA',        tr:'MAKARNA',             grade:8, diff:1, unit:3 },
  { en:'VEGETABLE',    tr:'SEBZE',               grade:8, diff:1, unit:3 },
  { en:'MELT',         tr:'ERİMEK',              grade:8, diff:2, unit:3 },
  { en:'CUT',          tr:'KESMEK',              grade:8, diff:1, unit:3 },
  { en:'CRACK',        tr:'KIRMAK',              grade:8, diff:2, unit:3 },
  { en:'BREAK',        tr:'KIRMAK',              grade:8, diff:2, unit:3 },
  { en:'STEP',         tr:'ADIM',                grade:8, diff:2, unit:3 },

  // ─── GRADE 8 UNIT 4 ──────────────────────────────────────────────────────────
  { en:'TALK FACE TO FACE', tr:'YÜZYÜZE KONUŞMAK',   grade:8, diff:2, unit:4 },
  { en:'WRITE A LETTER',    tr:'MEKTUP YAZMAK',       grade:8, diff:2, unit:4 },
  { en:'MAKE A PHONE CALL', tr:'TELEFON ETMEK',       grade:8, diff:1, unit:4 },
  { en:'SMOKE SIGNAL',      tr:'DUMAN İŞARETİ',       grade:8, diff:3, unit:4 },
  { en:'TEXT A MESSAGE',    tr:'MESAJ ATMAK',          grade:8, diff:1, unit:4 },
  { en:'SEND A MESSAGE',    tr:'MESAJ GÖNDERMEK',      grade:8, diff:1, unit:4 },
  { en:'TELEGRAM MACHINE',  tr:'TELGRAF MAKİNESİ',    grade:8, diff:3, unit:4 },
  { en:'USE SOCIAL NETWORKS',tr:'SOSYAL MEDYA KULLANMAK', grade:8, diff:2, unit:4 },
  { en:'MESSENGER BIRD',    tr:'GÜVERCİN İLE MESAJ',  grade:8, diff:3, unit:4 },
  { en:'SEND AN E-MAIL',    tr:'E-POSTA GÖNDERMEK',   grade:8, diff:1, unit:4 },
  { en:'HAVE A VIDEO CHAT', tr:'VİDEOLU GÖRÜŞME',     grade:8, diff:2, unit:4 },
  { en:'LEAVE A VOICEMAIL', tr:'SESLİ MESAJ BIRAKMAK', grade:8, diff:3, unit:4 },
  { en:'PRINTING MACHINE',  tr:'YAZICI / MATBAA',     grade:8, diff:2, unit:4 },
  { en:'AVAILABLE',         tr:'MÜSAİT',              grade:8, diff:2, unit:4 },
  { en:'CONNECT',           tr:'BAĞLANMAK',            grade:8, diff:1, unit:4 },
  { en:'CONTACT',           tr:'İLETİŞİME GEÇMEK',    grade:8, diff:2, unit:4 },
  { en:'DIAL',              tr:'NUMARA ÇEVİRMEK',      grade:8, diff:2, unit:4 },
  { en:'BUSY',              tr:'MEŞGUL',              grade:8, diff:1, unit:4 },
  { en:'ENGAGED',           tr:'MEŞGUL',              grade:8, diff:2, unit:4 },
  { en:'KEEP IN TOUCH',     tr:'İLETİŞİMDE KALMAK',   grade:8, diff:2, unit:4 },
  { en:'GET IN TOUCH',      tr:'İLETİŞİME GEÇMEK',    grade:8, diff:2, unit:4 },
  { en:'HANG ON',           tr:'BEKLEMEK',             grade:8, diff:1, unit:4 },
  { en:'HOLD ON',           tr:'BEKLEMEK',             grade:8, diff:1, unit:4 },
  { en:'HOLD THE LINE',     tr:'HATTA BEKLEMEK',       grade:8, diff:2, unit:4 },
  { en:'HANG UP',           tr:'TELEFONU KAPATMAK',    grade:8, diff:1, unit:4 },
  { en:'MEMO',              tr:'NOT',                  grade:8, diff:2, unit:4 },
  { en:'PICK UP',           tr:'TELEFONU AÇMAK',       grade:8, diff:1, unit:4 },
  { en:'ANSWER',            tr:'CEVAP VERMEK',          grade:8, diff:1, unit:4 },
  { en:'REPLY',             tr:'YANIT VERMEK',          grade:8, diff:1, unit:4 },
  { en:'PUT SOMEONE THROUGH',tr:'BAĞLAMAK',            grade:8, diff:3, unit:4 },
  { en:'CALL CENTER',       tr:'ÇAĞRI MERKEZİ',        grade:8, diff:2, unit:4 },
  { en:'REPEAT',            tr:'TEKRARLAMAK',           grade:8, diff:1, unit:4 },
  { en:'SPEAK LOUDER',      tr:'DAHA YÜKSEK SES',      grade:8, diff:2, unit:4 },
  { en:'LEAVE A MESSAGE',   tr:'MESAJ BIRAKMAK',        grade:8, diff:1, unit:4 },
  { en:'SENDER',            tr:'GÖNDEREN',             grade:8, diff:1, unit:4 },
  { en:'RECEIVER',          tr:'ALAN KİŞİ',            grade:8, diff:1, unit:4 },
  { en:'COMMUNICATION',     tr:'İLETİŞİM',             grade:8, diff:2, unit:4 },
  { en:'TRANSMISSION',      tr:'İLETİM',               grade:8, diff:3, unit:4 },
  { en:'UNAVAILABLE',       tr:'MÜSAİT DEĞİL',         grade:8, diff:2, unit:4 },
  { en:'CELL PHONE',        tr:'CEP TELEFONU',          grade:8, diff:1, unit:4 },
  { en:'MOBILE',            tr:'CEP TELEFONU',          grade:8, diff:1, unit:4 },
  { en:'APPLICATION',       tr:'UYGULAMA',             grade:8, diff:2, unit:4 },
  { en:'APP',               tr:'UYGULAMA',             grade:8, diff:1, unit:4 },
  { en:'APPOINTMENT',       tr:'RANDEVU',              grade:8, diff:2, unit:4 },
  { en:'OUT OF ORDER',      tr:'BOZUK',                grade:8, diff:2, unit:4 },
  { en:'INFORMATION',       tr:'BİLGİ',                grade:8, diff:1, unit:4 },
  { en:'INTERACTION',       tr:'ETKİLEŞİM',            grade:8, diff:3, unit:4 },
  { en:'CONFIRM',           tr:'ONAYLAMAK',             grade:8, diff:2, unit:4 },
  { en:'CUSTOMER',          tr:'MÜŞTERİ',              grade:8, diff:1, unit:4 },
  { en:'CONVERSATION',      tr:'KONUŞMA',              grade:8, diff:2, unit:4 },
  { en:'APPROXIMATELY',     tr:'YAKLAŞIK OLARAK',       grade:8, diff:3, unit:4 },
  { en:'NEARLY',            tr:'NEREDEYSE',            grade:8, diff:2, unit:4 },
  { en:'BAD LINE',          tr:'KÖTÜ BAĞLANTI',         grade:8, diff:2, unit:4 },
  { en:'CALL',              tr:'ARAMAK',               grade:8, diff:1, unit:4 },
  { en:'FLIGHT',            tr:'UÇUŞ',                grade:8, diff:1, unit:4 },
  { en:'SINGLE TICKET',     tr:'GİDİŞ BİLETİ',         grade:8, diff:2, unit:4 },
  { en:'RETURN TICKET',     tr:'GİDİŞ-DÖNÜŞ BİLETİ',  grade:8, diff:2, unit:4 },

  // ─── ANIMALS (grade:0, unit:11) ───────────────────────────────────────────────
  { en:'EAGLE',        tr:'KARTAL',              grade:0, diff:2, unit:11 },
  { en:'ELEPHANT',     tr:'FİL',                 grade:0, diff:1, unit:11 },
  { en:'SNAKE',        tr:'YILAN',               grade:0, diff:1, unit:11 },
  { en:'GIRAFFE',      tr:'ZÜRAFa',              grade:0, diff:1, unit:11 },
  { en:'PARROT',       tr:'PAPAĞAN',             grade:0, diff:1, unit:11 },
  { en:'LION',         tr:'ASLAN',               grade:0, diff:1, unit:11 },
  { en:'TURTLE',       tr:'KAPLUMBAĞA',           grade:0, diff:1, unit:11 },
  { en:'FISH',         tr:'BALIK',               grade:0, diff:1, unit:11 },
  { en:'TIGER',        tr:'KAPLAN',              grade:0, diff:2, unit:11 },
  { en:'DOLPHIN',      tr:'YUNUS',               grade:0, diff:1, unit:11 },
  { en:'SHARK',        tr:'KÖPEK BALIĞI',         grade:0, diff:1, unit:11 },
  { en:'WHALE',        tr:'BALİNA',              grade:0, diff:1, unit:11 },
  { en:'HAWK',         tr:'ŞAHIN',               grade:0, diff:3, unit:11 },
  { en:'ALLIGATOR',    tr:'ALİGATÖR',            grade:0, diff:3, unit:11 },
  { en:'FALCON',       tr:'DOĞAN',               grade:0, diff:3, unit:11 },
  { en:'CHEETAH',      tr:'ÇİTA',                grade:0, diff:2, unit:11 },
  { en:'CROCODILE',    tr:'TİMSAH',              grade:0, diff:3, unit:11 },
  { en:'KANGAROO',     tr:'KANGURU',             grade:0, diff:2, unit:11 },
  { en:'LIZARD',       tr:'KERTENKELE',           grade:0, diff:3, unit:11 },
  { en:'HIPPO',        tr:'SU AYĞIRI',            grade:0, diff:2, unit:11 },
  { en:'OSTRICH',      tr:'DEVEKUŞu',            grade:0, diff:3, unit:11 },
  { en:'RHINO',        tr:'GERGEDAN',             grade:0, diff:3, unit:11 },
  { en:'POLAR BEAR',   tr:'KUTUP AYISI',          grade:0, diff:2, unit:11 },

  // ─── FOODS & DRINKS (grade:0, unit:12) ───────────────────────────────────────
  { en:'BAGEL',        tr:'SİMİT',               grade:0, diff:2, unit:12 },
  { en:'BUTTER',       tr:'TEREYAĞI',            grade:0, diff:1, unit:12 },
  { en:'CEREAL',       tr:'TAHIL GEVREĞİ',        grade:0, diff:1, unit:12 },
  { en:'CROISSANT',    tr:'KROİSAN',             grade:0, diff:2, unit:12 },
  { en:'EGG',          tr:'YUMURTA',             grade:0, diff:1, unit:12 },
  { en:'FRUIT JUICE',  tr:'MEYVE SUYU',           grade:0, diff:1, unit:12 },
  { en:'JAM',          tr:'REÇEL',               grade:0, diff:1, unit:12 },
  { en:'OMELETTE',     tr:'OMLET',               grade:0, diff:2, unit:12 },
  { en:'MUFFIN',       tr:'MAFİN',               grade:0, diff:1, unit:12 },
  { en:'PANCAKE',      tr:'KREP',                grade:0, diff:1, unit:12 },
  { en:'SAUSAGE',      tr:'SOSİS',               grade:0, diff:1, unit:12 },
  { en:'NUTRITIOUS',   tr:'BESLEYİCİ',           grade:0, diff:3, unit:12 },
  { en:'TEA',          tr:'ÇAY',                 grade:0, diff:1, unit:12 },
  { en:'COFFEE',       tr:'KAHVE',               grade:0, diff:1, unit:12 },
  { en:'MILK',         tr:'SÜT',                 grade:0, diff:1, unit:12 },
  { en:'TOMATO',       tr:'DOMATES',             grade:0, diff:1, unit:12 },
  { en:'POTATO',       tr:'PATATES',             grade:0, diff:1, unit:12 },
  { en:'CHEESE',       tr:'PEYNİR',              grade:0, diff:1, unit:12 },
  { en:'SALAMI',       tr:'SALAM',               grade:0, diff:2, unit:12 },
  { en:'CUCUMBER',     tr:'SALATALIK',            grade:0, diff:1, unit:12 },
  { en:'HONEY',        tr:'BAL',                 grade:0, diff:1, unit:12 },
  { en:'BREAD',        tr:'EKMEK',               grade:0, diff:1, unit:12 },
  { en:'GARLIC',       tr:'SARIMSAK',            grade:0, diff:2, unit:12 },
  { en:'BEANS',        tr:'FASULYE',             grade:0, diff:1, unit:12 },
  { en:'ONION',        tr:'SOĞAN',               grade:0, diff:1, unit:12 },
  { en:'OLIVES',       tr:'ZEYTİN',              grade:0, diff:1, unit:12 },
  { en:'SUGAR',        tr:'ŞEKER',               grade:0, diff:1, unit:12 },
  { en:'SALT',         tr:'TUZ',                 grade:0, diff:1, unit:12 },

];
