// CLASH OF WORDS — Kelime Kategorileri
// Her kategori için geçerli İngilizce kelime listesi.
// Yeni kelime eklemek için ilgili diziye büyük harfle ekle.

const WORD_CATEGORIES = {

  "ANIMALS": [
    "ANT","APE","BAT","BEE","BOA","COD","COW","DOE","DOG","EEL","ELK","EMU","FLY","FOX",
    "GNU","HEN","HOG","JAY","OX","PIG","RAM","RAT","YAK","BEAR","BIRD","BULL","CALF",
    "CLAM","COLT","CRAB","CROW","DEER","DOVE","DUCK","FISH","FLEA","FROG","GULL","HARE",
    "HAWK","IBIS","KITE","LAMB","LION","LYNX","MINK","MOLE","MOTH","MULE","NEWT","PONY",
    "PUMA","SEAL","SLUG","SWAN","TOAD","VOLE","WASP","WOLF","WORM","WREN","BISON","COBRA",
    "CRANE","EAGLE","FINCH","GECKO","GOAT","GOOSE","HERON","HORSE","HYENA","LLAMA","MOOSE",
    "MOUSE","OTTER","PANDA","QUAIL","RAVEN","ROBIN","SHARK","SHEEP","SKUNK","SLOTH","SNAKE",
    "TIGER","TROUT","VIPER","WHALE","ZEBRA","BADGER","BEAVER","CANARY","DONKEY","FALCON",
    "FERRET","JAGUAR","LIZARD","MAGPIE","MONKEY","PARROT","PIGEON","RABBIT","SALMON","SHRIMP",
    "SPIDER","TOUCAN","TURTLE","WALRUS","CONDOR","COYOTE","CUCKOO","DOLPHIN","GORILLA",
    "HAMSTER","LEOPARD","LOBSTER","OCTOPUS","PENGUIN","PEACOCK","PELICAN","PIRANHA","ROOSTER",
    "SPARROW","VULTURE","CHEETAH","GIRAFFE","BUFFALO","PANTHER","CROCODILE","ELEPHANT",
    "FLAMINGO","KANGAROO","HEDGEHOG","RHINOCEROS","CHAMELEON","ALLIGATOR","CATERPILLAR",
    "SCORPION","TORTOISE","WOLVERINE","PLATYPUS","SQUIRREL","CHIPMUNK","WARTHOG","MANDRILL",
    "CAMEL","HIPPO","RHINO","OSTRICH","KOALA","RACCOON","CHIMP","IGUANA","PORCUPINE","TURKEY",
    "JACKAL","LEMUR","MEERKAT","ORANGUTAN","REINDEER","TAPIR","WEASEL","ARMADILLO","ANTELOPE",
    "BARRACUDA","ANACONDA","CENTIPEDE","GAZELLE","TERMITE","SEAHORSE","WOODPECKER","OX","SEAGULL"
  ],

  "PLACES": [
    "BAR","BAY","BOG","DEN","FEN","GYM","INN","LAB","PIT","PUB","SPA","ZOO","ARCH","BANK",
    "BARN","CAFE","CAMP","CITY","CLUB","DOCK","FARM","FORT","GATE","HALL","HILL","HOME",
    "JAIL","LAKE","MALL","MINE","MARKET","MOOR","PARK","PIER","POND","POOL","PORT","ROAD","SHOP",
    "SHED","TOWN","VALE","YARD","ABBEY","ATTIC","BEACH","BROOK","CANAL","CAVE","CLIFF",
    "COURT","CREEK","DELTA","DEPOT","DINER","FIELD","FJORD","FORGE","GLADE","GORGE","GROVE",
    "HAVEN","HOTEL","HOUSE","INLET","ISLET","JETTY","LODGE","MANOR","MARSH","MOUNT","OASIS",
    "PLAIN","PLAZA","RANCH","RIDGE","RIVER","SALON","SHACK","SHORE","SLOPE","STORE","SWAMP","SUPERMARKET",
    "TOWER","TRAIL","VAULT","VILLA","WHARF","WOODS","BRIDGE","CASTLE","CELLAR","CHURCH",
    "CIRCUS","CLINIC","DESERT","FOREST","GARAGE","GARDEN","HARBOR","ISLAND","JUNGLE","MUSEUM",
    "OFFICE","PALACE","PRISON","RESORT","SCHOOL","SQUARE","STREAM","STREET","STUDIO","SUBURB",
    "TEMPLE","VALLEY","VILLAGE","AIRPORT","BALCONY","LIBRARY","FACTORY","STADIUM","STATION",
    "THEATER","BEDROOM","KITCHEN","COTTAGE","PYRAMID","GLACIER","VOLCANO","DUNGEON","MEADOW",
    "ORCHARD","QUARRY","TUNNEL","CANYON","PLATEAU","HARBOUR","POLICE STATION","FIRE STATION","MUNICIPALITY",
    "TOWN HALL","PHARMACY","DRUG STORE","CHEMIST",
    "CITY HALL","GOVERNORSHIP","AMUSEMENT PARK","ART GALLERY","BAKERY","GROCER",
    "GAME STORE","MUSIC STORE","DEPARTMENT STORE","GREENGROCER","MOVIE THEATER",
    "SHOPPING MALL","POST OFFICE","HOSPITAL","FLORIST","DENTIST","TOY SHOP",
    "SHOE SHOP","COFFEE SHOP","NEWSAGENT","BOOKSHOP","CONCERT HALL",
    "TRAVEL AGENCY","BUTCHER",
  ],

  "SCHOOL OBJECTS": [
    "PEN","MAP","GEL","BOOK","DESK","GLUE","TAPE","TRAY","TUBE","CHALK","RULER","ERASER",
    "GLOBE","ATLAS","CLOCK","BINDER","FOLDER","PENCIL","MARKER","STAPLER","COMPASS","SCANNER",
    "PRINTER","MONITOR","KEYBOARD","NOTEBOOK","TEXTBOOK","SCISSORS","BACKPACK","CALCULATOR",
    "PROJECTOR","WHITEBOARD","BLACKBOARD","HIGHLIGHTER","SHARPENER","DICTIONARY","PROTRACTOR",
    "FLASHCARD","CLIPBOARD","THUMBTACK","PUSHPIN","EASEL","LOCKER","BULLETIN BOARD","INDEX CARD",
    "PENCIL CASE","STICKY NOTE","RUBBER BAND","SCHOOL BAG","PAINT BRUSH","WATERCOLOUR",
    "CRAYON","STICKER","WORKSHEET","REPORT CARD","TIMETABLE","SCHEDULE","PAPER","SMARTBOARD","PENCASE",
    "WORKBOOK","CALENDAR","FILE","ABACUS","LAPTOP","TABLET","SKETCHBOOK","GLUESTICK","PAPERCLIP","ATTACH",
    "WHITE BOARD","SMART BOARD","BLACK BOARD","PAINTBRUSH","PAINT BRUSH","BOARD MARKER","MARKER","BOARDMARKER",
    "SCHOOLBAG","GLUE STICK","RUBBER"
  ],

  "FURNITURE": [
    "BED","MAT","RUG","SOFA","DESK","RACK","SHELF","STOOL","CHAIR","COUCH","TABLE","BENCH",
    "DRESSER","CABINET","ARMCHAIR","BOOKCASE","WARDROBE","NIGHTSTAND","LAMP","PLAYSTATION",
    "SIDEBOARD","CUPBOARD","BOOKSHELF","BUNK BED","CHEST","DRAWER","FOOTSTOOL","RECLINER",
    "LOVESEAT","BARSEAT","BARSTOOL","COAT RACK","COFFEE TABLE","DINING TABLE","WORK DESK",
    "BEDSIDE TABLE","DISPLAY CASE","STORAGE BOX","FOLDING CHAIR","ROCKING CHAIR","WALL UNIT",
    "TV STAND","TELEVISION","DRAWER","DRAWERS","DESK LAMP","FILE CABINET","SHOE RACK","SHOERACK",
    "VANITY","ENDTABLE","ARMOIRE"
  ],

  "VEHICLES": [
    "CAR","BUS","VAN","CAB","JET","SUB","BIKE","BOAT","SHIP","TRAM","TAXI","JEEP","BLIMP",
    "CANOE","CRANE","FERRY","KAYAK","LORRY","PLANE","TRAIN","TRUCK","YACHT","BARGE","BUGGY",
    "COUPE","RACER","ROCKET","SCOOTER","TRACTOR","TANKER","GONDOLA","MINIVAN","TUGBOAT",
    "WARSHIP","AIRCRAFT","LIFEBOAT","MONORAIL","SPEEDBOAT","AMBULANCE","CABLE CAR","FIRE TRUCK",
    "FIRETRUCK","LIMOUSINE","SUBMARINE","SKATEBOARD","WHEELCHAIR","MOTORCYCLE","HELICOPTER",
    "CATAMARAN","HOVERCRAFT","SNOWMOBILE","DOUBLE DECKER","STEAM TRAIN","FREIGHT TRAIN","PICKUP TRUCK",
    "SUV","SEDAN","WAGON","HATCHBACK","BULDOZER","EXCAVATOR","FORKLIFT","DRONE","GLIDER","SPACESHIP",
    "SHUTTLE","SPACE SHUTTLE","JETSKI","JET SKI","CARAVAN","CAMPER VAN","MOTORBOAT","BICYCLE","MOPED",
    "ROLLERBLADES","ROLLER BLADES","CARRIAGE","SKATES"
  ],

  "CLOTHING": [
    "SHOE","CAP","TIE","HAT","BELT","BOOT","COAT","GOWN","ROBE","SOCK","SUIT","VEST","WRAP",
    "APRON","BLOUSE","CLOAK","DENIM","DRESS","JEANS","SKIRT","SHIRT","SCARF","SHAWL","SHORTS",
    "GLOVES","HOODIE","JACKET","TIGHTS","SHORTS","TRUNKS","TURBAN","BIKINI","BLAZER",
    "JUMPER","SANDAL","SHORTS","BLOUSE","SNEAKER","SWEATER","TRAINER","UNIFORM","WETSUIT",
    "CARDIGAN","LEGGINGS","OVERCOAT","RAINCOAT","SWIMSUIT","TRACKSUIT","UNDERWEAR","WAISTCOAT",
    "TROUSERS","PYJAMAS","PAJAMAS","STOCKINGS","FLIP FLOPS","POLO SHIRT","SWEATSHIRT",
    "TANK TOP","TURTLENECK","WINDBREAKER","DRESSING GOWN","SPORT SHOES","HIGH HEELS","LOAFERS",
    "BEANIE","BERET","VISOR","MITTENS","SLIPPERS","CLOGS","OVERALLS","JUMPSUIT","SNEAKERS","TRAINERS",
    "HELMET","KIMONO","TUXEDO","NIGHTGOWN","GOWN","BALACLAVA","HANDKERCHIEF","BANDANA","CORSET","CROP TOP",
    "CROPTOP"
    

  ],

  "GAMES/SPORTS": [
    "GOLF","POLO","POOL","SURF","YOGA","DARTS","CHESS","RUGBY","JUDO","LUDO","TENNIS",
    "BOXING","KARATE","SOCCER","ROWING","SKIING","CYCLING","SAILING","ARCHERY","BOWLING",
    "CRICKET","CROQUET","FENCING","FISHING","HIKING","HOCKEY","HUNTING","JOGGING","RACING",
    "RIDING","RUNNING","SKATING","SURFING","SWIMMING","TREKKING","WRESTLING","BASEBALL",
    "HANDBALL","FOOTBALL","HURLING","JUMPING","LACROSSE","MARATHON","VOLLEYBALL","BADMINTON",
    "BASKETBALL","GYMNASTICS","PAINTBALL","TAEKWONDO","SNOOKER","BILLIARDS","NETBALL",
    "SOFTBALL","DISCUS","JAVELIN","TRIATHLON","SQUASH","SPRINTING","DECATHLON","SNOWBOARD",
    "SKATEBOARD","WATERPOLO","KICKBOXING","MOTOCROSS","PENTATHLON","WEIGHTLIFTING","DOGE BALL",
    "DODGEBALL","KAYAKING","RAFTING","CLIMBING","ICE SKATING","CANOEING","SKYDIVING","SCUBA",
    "SCUBA DIVING","WINDSURFING","WIND SURFING","PARAGLIDING","HANG GLIDING","TABLE TENNIS",
    "PING PONG","BODY BUILDING","SUMO","SUMO WRESTLING","CHECKERS","BACKGAMMON","PARKOUR","PARKOUR RUNNING",
    "TAG","HIDE AND SEEK","HOPSCOTCH","TIC-TAC-TOE","TIC TAC TOE","JUMP ROPE","MUSICAL CHAIRS",
    "CHARADES","ROCK PAPER SCISSORS","COPS AND ROBBERS","RED LIGHT GREEN LIGHT",
  ],

  "COUNTRIES": [
    "CHAD","CUBA","FIJI","IRAN","IRAQ","LAOS","MALI","OMAN","PERU","TOGO","BENIN","CHILE",
    "CHINA","EGYPT","FRANCE","GHANA","GREECE","INDIA","ITALY","JAPAN","KENYA","LIBYA","NEPAL",
    "NIGER","NORWAY","QATAR","RUSSIA","SPAIN","SUDAN","SWEDEN","TURKEY","UGANDA","ANGOLA",
    "ARMENIA","AUSTRIA","BAHRAIN","BELARUS","BELGIUM","BHUTAN","BOLIVIA","BRUNEI","BURUNDI",
    "CANADA","CROATIA","DENMARK","ECUADOR","ERITREA","ESTONIA","FINLAND","GEORGIA","GERMANY",
    "HUNGARY","ICELAND","IRELAND","ISRAEL","JAMAICA","JORDAN","KUWAIT","LATVIA","LEBANON",
    "LIBERIA","MOROCCO","MYANMAR","NAMIBIA","NIGERIA","PAKISTAN","PANAMA","POLAND","PORTUGAL",
    "ROMANIA","RWANDA","SENEGAL","SERBIA","SOMALIA","SURINAME","TANZANIA","THAILAND","TUNISIA",
    "UKRAINE","URUGUAY","VIETNAM","YEMEN","ZAMBIA","ALBANIA","ALGERIA","COLOMBIA","ETHIOPIA",
    "MALAYSIA","MALDIVES","MOLDOVA","MONGOLIA","NICARAGUA","SINGAPORE","SLOVAKIA","SLOVENIA",
    "TAJIKISTAN","VENEZUELA","ZIMBABWE","INDONESIA","LUXEMBOURG","PHILIPPINES","SWITZERLAND",
    "NETHERLANDS","ARGENTINA","AUSTRALIA","CAMBODIA","CAMEROON","GUATEMALA","USA","ENGLAND","UNITED KINGDOMS",
    "UNITED KINGDOM","BRAZIL","MEXICO","SOUTH AFRICA","AFGHANISTAN","PARAGUAY","BANGLADESH","MADAGASCAR",
    "TURKMENISTAN","UZBEKISTAN","AZERBAIJAN","BOSNIA","BULGARIA","CYPRUS","VATICAN","TURKIYE",
  ],

  "FRUIT/VEGETABLES": [
    "FIG","PEA","YAM","BEET","CORN","KALE","KIWI","LEEK","LIME","PEAR","PLUM","DATE","BEAN",
    "OKRA","DILL","GARLIC","GRAPE","GUAVA","LEMON","MANGO","MELON","OLIVE","ONION","PEACH",
    "RADISH","TURNIP","APPLE","AVOCADO","BANANA","CARROT","CHERRY","CELERY","TOMATO","POTATO",
    "ORANGE","PAPAYA","PEPPER","SQUASH","SPINACH","APRICOT","CABBAGE","PUMPKIN","LETTUCE",
    "COCONUT","PINEAPPLE","BLUEBERRY","BROCCOLI","CUCUMBER","EGGPLANT","MUSHROOM","RASPBERRY",
    "STRAWBERRY","WATERMELON","BLACKBERRY","GRAPEFRUIT","CAULIFLOWER","ARTICHOKE","ASPARAGUS",
    "BEETROOT","CHESTNUT","COURGETTE","CRANBERRY","GOOSEBERRY","MANDARIN","NECTARINE",
    "TANGERINE","POMEGRANATE","PARSLEY","GINGER","FENNEL","AUBERGINE","CANTALOUPE",
    "PASSIONFRUIT","SWEETCORN","WATERCRESS","ENDIVE","RHUBARB","PEPPERCORN","ZUCCHINI","PEANUT",
    "WALNUT","ALMOND","PISTACHIO","LYCHEE","DRAGON FRUIT","DRAGONFRUIT","SWEET POTATO","SWEETPOTATO",
    "PERSIMMON",
  ],

  "BEVERAGES": [
    "ALE","GIN","RUM","TEA","BEER","COKE","MILK","SODA","WINE","WATER","COCOA","CIDER",
    "COFFEE","BRANDY","EGGNOG","LEMONADE","MILKSHAKE","SMOOTHIE","WHISKEY","CHAMPAGNE",
    "LIMEADE","KOMBUCHA","MOCKTAIL","COCKTAIL","ESPRESSO","CAPPUCCINO","FRAPPE","LASSI",
    "MEAD","PUNCH","SQUASH","TONIC","VODKA","BOURBON","SANGRIA","PROSECCO","CORDIAL",
    "NECTAR","JUICE","SHAKE","FIZZ","BREW","TODDY","LATTE","MOCHA","AMERICANO","HORCHATA",
    "ICE TEA","HOT CHOCOLATE","ENERGY DRINK","COLA","SPRITE","COCA COLA","PEPSI",
    "AYRAN","MINERAL WATER","SODA","BUBBLE TEA","MACCHIATO","TEQUILA","SAKE","SOJU","MATCHA",
    "CHAI","ROOT BEER","GINGER ALE","JUICE"


  ],

  "ACTIONS": [
    "ADD","ASK","BEG","BET","BID","BITE","BLOW","BOIL","BRAG","BRING","BUILD","BURN","BUY",
    "CALL","CATCH","CHASE","CHEW","CLAP","CLEAN","CLIMB","COOK","COPY","CRAWL","CRY","CUT",
    "DIG","DIVE","DRAG","DRAW","DREAM","DRINK","DRIVE","DROP","EAT","FALL","FIGHT","FIND",
    "FIX","FLY","FOLD","GIVE","GRAB","GROW","HELP","HIDE","HIT","HOLD","JUMP","KICK","KNOCK",
    "LAUGH","LEAP","LIFT","LOOK","LOSE","MAKE","MISS","MOVE","PAINT","PICK","PLAN","PLAY",
    "PULL","PUSH","READ","RIDE","RUN","SAVE","SELL","SEND","SING","SINK","SKIP","SLEEP",
    "SLIDE","SMILE","SPIN","STAND","STOP","SWIM","TAKE","TALK","THROW","TURN","WALK","WASH",
    "WAVE","WIN","WORK","WRITE","ZOOM","BAKE","BARK","BEND","BURY","DARE","DROWN","DUNK",
    "FAIL","FEEL","FILL","FIRE","FLEE","FLOW","HALT","HANG","HEAL","HEAT","HIKE","HUNT",
    "JOIN","LEAN","LEND","LOCK","MEND","OPEN","PACK","POUR","PRAY","RACE","ROLL","RUSH",
    "SAIL","SCAN","SEAL","SLAM","SOAK","SORT","STIR","STORE","SWEEP","SWING","TEAR","TEST",
    "TOSS","TRIM","WAKE","WRAP","SPRINT","MARCH","CROUCH","WHISPER","SHOUT","STOMP","SALUTE","GO"
  ],

  "ADJECTIVES": [
    "BIG","SMALL","FAT","FIT","HOT","ICY","LOW","MAD","OLD","RED","SAD","SHY","SLY","TALL","TINY",
    "UGLY","WARM","WEAK","WIDE","WILD","BOLD","BUSY","CALM","COLD","COOL","CUTE","DARK",
    "DEAD","DEAF","DEEP","DULL","EASY","FAIR","FAST","FINE","FIRM","FLAT","FREE","FULL",
    "GOOD","HARD","HIGH","HUGE","KIND","LAZY","LEAN","MEAN","MILD","NEAT","NICE","PALE",
    "POOR","PURE","RARE","RICH","RIPE","RUDE","SAFE","SICK","SLIM","SLOW","SOFT","SORE",
    "SOUR","TAME","THIN","TORN","VAST","WARY","WISE","YOUNG","AWFUL","BASIC","BLACK","BLANK",
    "BRAVE","BRIEF","BROAD","BROWN","BUMPY","CHEAP","CLEAR","CLOSE","COZY","CRAZY","CRISP",
    "CRUEL","CURLY","DIRTY","DIZZY","DUSTY","EMPTY","FANCY","FRESH","FUNNY","FUZZY","GENTLE",
    "GRAND","GREAT","GREEN","GRUMPY","HAPPY","HARSH","HEAVY","HUMID","LIGHT","LIVELY","LOUD",
    "LUCKY","MESSY","MODERN","NOBLE","NOISY","PLAIN","PROUD","QUICK","QUIET","RAPID","READY",
    "ROUGH","ROUND","ROYAL","RUSTY","SCARY","SHARP","SHINY","SHORT","SILLY","SIMPLE","SMART",
    "SOLID","SPICY","STICKY","SUNNY","SWEET","SWIFT","THICK","TIGHT","TOUGH","USEFUL","VIVID",
    "WICKED","WITTY","CLEVER","TENDER","FIERCE","HUMBLE","HONEST","POLITE","STRICT","ANGRY",
    "BRIGHT","FRIENDLY","HUNGRY","PRETTY","SMOOTH","STRANGE","STURDY","SLEEPY","TASTY",
    "CLUMSY","CLEVER","SELFISH","GENEROUS","GREEDY","CHEERFUL","GRUMPY","MOODY","BOSSY",
    "STUBBORN","PATIENT","IMPATIENT","CREATIVE","CURIOUS","CONFIDENT","SHY","TIMID",
    "BRAVE","COWARDLY","HONEST","DISHONEST","LOYAL","JEALOUS","ARROGANT","MODEST",
    "CARING","RUDE","POLITE","NAUGHTY","OBEDIENT","DISOBEDIENT","HARDWORKING","LAZY",
    "SERIOUS","PLAYFUL","SENSITIVE","TALKATIVE","QUIET","SOCIABLE","AGGRESSIVE",
    "CHARMING","RELIABLE","IRRESPONSIBLE","INDEPENDENT","COOPERATIVE","WITTY","SARCASTIC",
    "OPTIMISTIC","PESSIMISTIC","AMBITIOUS","EASYGOING","NERVOUS","CHEERFUL","TRUSTWORTHY"
  ],

  "JOBS": [
    "VET","COP","NURSE","CHEF","COOK","MAID","MONK","PILOT","JUDGE","TUTOR","TAILOR","BARBER",
    "BANKER","BROKER","BUTLER","DRIVER","EDITOR","FARMER","FISHER","LAWYER","MENTOR","PASTOR",
    "PORTER","PRIEST","SINGER","TRADER","WAITER","WRITER","ARTIST","AUTHOR","DANCER","DEALER",
    "DOCTOR","GROCER","HELPER","MANAGER","MILLER","MINER","MODEL","PAINTER","PLUMBER","RANGER",
    "SAILOR","SOLDIER","SURGEON","TEACHER","TRAINER","WELDER","WARDEN","WORKER","CASHIER",
    "CLEANER","COURIER","BUILDER","CHEMIST","CYCLIST","DENTIST","FLORIST","JANITOR","MECHANIC",
    "MUSICIAN","NOVELIST","DIPLOMAT","ENGINEER","SURVEYOR","LIBRARIAN","ARCHITECT","ASTRONAUT",
    "CARPENTER","HISTORIAN","JOURNALIST","PHARMACIST","POLITICIAN","PROFESSOR","THERAPIST",
    "ACCOUNTANT","BIOLOGIST","BOTANIST","DETECTIVE","ECONOMIST","GEOLOGIST","VETERINARIAN",
    "RECEPTIONIST","PSYCHOLOGIST","FIREFIGHTER","PARAMEDIC","ELECTRICIAN","PROGRAMMER","SCIENTIST"
  ],

  "ILLNESSES": [
    "FLU","ACNE","GOUT","COLD","COUGH","FEVER","MUMPS","EBOLA","RABIES","CANCER","SCURVY",
    "DENGUE","STROKE","ASTHMA","HERPES","ULCER","PLAGUE","TYPHUS","ANEMIA","ANGINA","AUTISM",
    "ARTHRITIS","CHOLERA","COLITIS","DIABETES","ECZEMA","EPILEPSY","MEASLES","MALARIA",
    "OBESITY","PNEUMONIA","PSORIASIS","TETANUS","MENINGITIS","DYSLEXIA","INSOMNIA","HEPATITIS",
    "INFLUENZA","LEUKEMIA","DEMENTIA","DEPRESSION","CHICKENPOX","BRONCHITIS","APPENDICITIS",
    "TUBERCULOSIS","HYPERTENSION","MIGRAINE","DYSENTERY","GLAUCOMA","ALZHEIMER","PARKINSON","EARACHE",
    "TOOTHACHE","BACKACHE","HEADACHE","BROKEN ARM","BROKEN LEG","COVID","AIDS","HIV","VERTIGO","ALLERGY",
    "ANXIETY","BIPOLAR","SMALLPOX"
  ],

  "LESSONS": [
    "ART","GYM","MATH","MUSIC","DRAMA","DANCE","DESIGN","ETHICS","FRENCH","GERMAN","HEALTH",
    "HISTORY","PHYSICS","SCIENCE","ENGLISH","BIOLOGY","CHEMISTRY","GEOGRAPHY","RELIGION",
    "SOCIOLOGY","ECONOMICS","PHILOSOPHY","PSYCHOLOGY","TECHNOLOGY","LITERATURE","MATHEMATICS",
    "INFORMATICS","WOODWORK","METALWORK","COMPUTING","TURKISH","CIVICS","ASTRONOMY","STATISTICS",
    "NUTRITION","MEDIA","ENVIRONMENTAL","PROGRAMMING","ACCOUNTING","ARCHITECTURE","SOCIAL",
    "SOCIAL STUDIES","SOCIAL SCIENCE","GEOMETRY","CODING","ROBOTICS","SPANISH","LATIN","ARTS","MATHS"
   
  ],

  "NATIONALITIES": [
    "ARABIAN","THAI","TURKISH","WELSH","IRISH","DUTCH","GREEK","CZECH","FRENCH","ITALIAN","KOREAN",
    "POLISH","GERMAN","DANISH","INDIAN","JAPANESE","CHINESE","RUSSIAN","SPANISH","SWEDISH",
    "TURKISH","AUSTRIAN","BELGIAN","BRITISH","CANADIAN","COLOMBIAN","CROATIAN","EGYPTIAN","ENGLISH",
    "FINNISH","GEORGIAN","GHANAIAN","HUNGARIAN","ICELANDIC","INDONESIAN","IRANIAN","IRAQI",
    "ISRAELI","JORDANIAN","KAZAKH","KENYAN","LATVIAN","LEBANESE","LITHUANIAN","MALAYSIAN",
    "MEXICAN","MOROCCAN","NIGERIAN","NORWEGIAN","PAKISTANI","PERUVIAN","PORTUGUESE","ROMANIAN",
    "SAUDI","SCOTTISH","SERBIAN","SINGAPOREAN","SLOVENIAN","SWISS","TUNISIAN","UKRAINIAN",
    "URUGUAYAN","VENEZUELAN","VIETNAMESE","ARMENIAN","AZERBAIJANI","BELARUSIAN","BOLIVIAN",
    "CHILEAN","CUBAN","ECUADORIAN","ETHIOPIAN","GUATEMALAN","HONDURAN"
  ],

  "DAILY ROUTINE": [
    "WAKE","WAKE UP","WASH FACE","GET DRESSED","EAT","SLEEP","STUDY","COOK","CLEAN","DRINK","SHOWER","SHAVE",
    "BRUSH TEETH","GO SHOPPING","WALK","READ","WRITE","EXERCISE","WORK","LUNCH","HAVE LUNCH","DINNER","HAVE DINNER","RELAX",
    "PRAY","MEDITATE","RIDE BIKE","HAVE SHOWER","HAVE BATH","TAKE A NAP",
    "WATER PLANTS","FEED PET","BATHE","COMB","FLOSS","NAP","REST","STRETCH","JOG","CYCLE","CYCLING",
    "SWIM","SWIMMING","ATTEND SCHOOL","BREAKFAST","HAVE BREAKFAST","EXERCISE",
    "SHOPPING","JOGGING","COOKING","COOK","COOK MEAL","CLEANING","CLEAN","MAKE BED","STUDYING","STUDY,","SLEEPING","GET UP"
  ],

  "COLOURS": [
    "RED","BLUE","GOLD","GREY","LIME","NAVY","PINK","PLUM","ROSE","RUBY","RUST","TEAL","AQUA","DARK BLUE",
    "AZURE","BEIGE","BLACK","BROWN","CORAL","CREAM","CRIMSON","EBONY","GREEN","HONEY","IVORY","NAVY BLUE",
    "KHAKI","LEMON","LILAC","MAUVE","OCHRE","OLIVE","PEACH","PEARL","SILVER","SLATE","TAUPE","GINGER",
    "UMBER","VIOLET","WHITE","YELLOW","AMBER","BRONZE","COBALT","COPPER","INDIGO","MAROON",
    "ORANGE","PURPLE","SALMON","SIENNA","TURQUOISE","LAVENDER","MAGENTA","CHARTREUSE",
    "VERMILLION","SCARLET","CYAN","JADE","MINT","MUSTARD","ONYX","TAN","TOPAZ"
  ],

  "BODY PARTS": [
    "ARM","EAR","EYE","GUM","HIP","JAW","LEG","LIP","RIB","TOE","BACK","BONE","CALF","CHIN",
    "FOOT","HAIR","HAND","HEAD","HEEL","KNEE","NAIL","NECK","NOSE","SHIN","SKIN","WRIST",
    "ANKLE","CHEEK","CHEST","ELBOW","HEART","LIVER","LUNG","MOUTH","SPINE","TEETH","THIGH",
    "THUMB","TONGUE","BRAIN","BROW","COLON","JOINT","KIDNEY","KNUCKLE","LARYNX","MUSCLE",
    "PELVIS","RETINA","SCALP","SHOULDER","STOMACH","TENDON","TEMPLE","THROAT","TONSIL",
    "BLADDER","EARDRUM","EYELID","FOREARM","FOREHEAD","KNEECAP","NOSTRIL","TRACHEA",
    "ABDOMEN","COLLARBONE","PANCREAS","APPENDIX","EYELASH","EYEBROW","ARMPIT","EARLOBE",
    "FINGERNAIL","TOENAIL","SHINBONE","KNEECAP","FINGER"
  ],

  "MOVIE TYPES": [
    "ACTION","COMEDY","HORROR","ROMANCE","THRILLER","MYSTERY","DRAMA","FANTASY","MUSICAL",
    "WESTERN","ANIMATED","DOCUMENTARY","ADVENTURE","ANIMATION","BIOGRAPHY","CRIME","FAMILY",
    "HISTORY","SPORTS","SPY","SUPERHERO","CARTOON",
    "WAR","ZOMBIE","HISTORICAL","PSYCHOLOGICAL","SUPERNATURAL","NOIR","ANTHOLOGY","DISASTER","POLITICAL",
    "ROMANTIC","SCI FI"
  ],

  "TIME": [
    "MORNING","AFTERNOON","EVENING","MIDNIGHT","SUNRISE","SUNSET","SUNDAY","WEDNESDAY",
    "DAWN","DUSK","NOON","SECOND","MINUTE","HOUR","DAY","WEEK","THURSDAY","FRIDAY","SATURDAY",
    "MONTH","YEAR","DECADE","CENTURY","MILLENNIUM","SEASON","JANUARY","FEBRUARY","MARCH",
    "SPRING","SUMMER","AUTUMN","WINTER","PAST","PRESENT","FUTURE","APRIL","MAY","JUNE","JULY",
    "CALENDAR","WEEKEND","YESTERDAY","TOMORROW","WEEKDAYS","TODAY","MONDAY","AUGUST","SEPTEMBER",
    "OCTOBER","NOVEMBER","DECEMBER","TUESDAY","NIGHT","MIDDAY","MIDWEEK","FORTNIGHT","ERA","EPOCH",
    "AGE","TIMELINE","MOMENT","ANNIVERSARY","DEADLINE","HOLIDAY","VACATION","TERM","SEMESTER","MIDTERM",
    "DAILY","HOURLY","YEARLY","WEEKLY","WEEKDAY","TONIGHT"
  ],

  "PARTIES": [
    "FEAST","THANKSGIVING","PROM","PICNIC","BBQ","DINNER","BUFFET","BRUNCH",
    "BANQUET","CARNIVAL","FESTIVAL","BIRTHDAY","WEDDING","CONCERT","FAREWELL",           
    "BARBECUE","BONFIRE","POTLUCK","REUNION","SLEEPOVER","HALLOWEEN","TAILGATE","COCKTAIL",
    "RECEPTION","MASQUERADE","GRADUATION","CELEBRATION","ANNIVERSARY","HOMECOMING",
    "SURPRISE","KARAOKE","DISCO","FUNDRAISER","CEREMONY","SLUMBER","KAREOKE",
    "CANDLE","CAKE","BIRTHDAY CAKE","CONFETTI","HAT","PARTY HAT","BALLOON","BALLOONS",
    "STREAMERS","STREAMER","BANNER","GIFT","PRESENT","RIBBON","WRAPPING PAPER",
    "INVITATION","INVITE","DECORATION","DECORATIONS","PINATA","GOODIE BAG","PARTY BAG",
    "NOISEMAKER","WHISTLE","SPARKLER","FIREWORK","FIREWORKS","CUPCAKE","PUNCH",
    "LEMONADE","JUICE","SNACK","CANDLES","WISHLIST","BIRTHDAY CARD","CARD",
    "TABLECLOTH","NAPKIN","PLATE","CUP","STRAW","BLOWER","PARTY BLOWER"
  ]

};

// ── BONUS KURAL KONTROLÜ ──────────────────────────────────
function checkBonusRule(bonusCategory, word) {
  const w = word.toUpperCase().replace(/\s+/g, '');
  const wf = word.toUpperCase().trim();
  switch (bonusCategory) {
    case "STARTS WITH A":       return wf.startsWith("A");
    case "STARTS WITH E":       return wf.startsWith("E");
    case "STARTS WITH M":       return wf.startsWith("M");
    case "STARTS WITH S":       return wf.startsWith("S");
    case "STARTS WITH T":       return wf.startsWith("T");
    case "STARTS WITH C":       return wf.startsWith("C");
    case "4 LETTERS":           return w.length === 4;
    case "5 LETTERS":           return w.length === 5;
    case "6 LETTERS":           return w.length === 6;
    case "MORE THAN 6 LETTERS": return w.length > 6;
    case "2 WORDS":             return wf.includes(" ");
    case "CONTAINS L":          return wf.includes("L");
    case "CONTAINS P":          return wf.includes("P");
    default:                    return false;
  }
}

// ── STEM & CANONICAL ──────────────────────────────────────
// Temel İngilizce çoğul/suffix soyma (yanlış pozitifi önlemek için
// sadece bilinen pattern'lere bakar, agresif değil)
function stemEnglish(w) {
  // w: UPPERCASE, boşuksuz
  // -IES → Y  (BABIES→BABY, COUNTRIES→COUNTRY)
  if (/IES$/.test(w) && w.length > 4) return w.slice(0, -3) + 'Y';
  // -VES → F  (KNIVES→KNIFE, LEAVES→LEAF)
  if (/VES$/.test(w) && w.length > 4) return w.slice(0, -3) + 'F';
  // -ES (sibilant stems: BRUSHES→BRUSH, MATCHES→MATCH, BOXES→BOX, BUSES→BUS)
  if (/ES$/.test(w) && w.length > 4) {
    const stem = w.slice(0, -2);
    if (/[SXZ]$/.test(stem) || /[SC]H$/.test(stem)) return stem;
  }
  // -S basic plural (CATS→CAT) — ama -SS sonları dokunma (DRESS,MISS,BOSS)
  if (/[^S]S$/.test(w) && w.length > 3) return w.slice(0, -1);
  return w;
}

// Kelimeyi canonical forma getirir: büyük harf + boşuksuz + stemlenmiş
function canonicalWord(w) {
  return stemEnglish(w.toUpperCase().trim().replace(/\s+/g, ''));
}

// ── KATEGORİ GEÇERLİLİK KONTROLÜ ─────────────────────────
function isWordValidForCategory(category, word) {
  const list = WORD_CATEGORIES[category];
  if (!list) return false;
  const w = word.toUpperCase().trim();

  // 1. Birebir eşleşme (mevcut davranış)
  if (list.includes(w)) return true;

  // 2. Boşluk normalizasyonu: GLUESTICK = GLUE STICK
  const wNoSp = w.replace(/\s+/g, '');
  if (list.some(d => d.replace(/\s+/g, '') === wNoSp)) return true;

  // 3. Çoğul toleransı: NUTS→NUT, BRUSHES→BRUSH, BABIES→BABY, KNIVES→KNIFE
  //    Hem input'u hem de sözlük kelimesini stem'leyip karşılaştır
  const wCanon = stemEnglish(wNoSp);
  if (wCanon !== wNoSp) {  // yalnızca stem farklıysa kontrol et (gereksiz döngüyü önler)
    if (list.some(d => {
      const dNoSp = d.toUpperCase().replace(/\s+/g, '');
      return dNoSp === wCanon || stemEnglish(dNoSp) === wCanon;
    })) return true;
  }

  return false;
}

// ── BONUS OLASILIKKONTROLü ────────────────────────────────
function isBonusPossibleForCategories(bonus, categories) {
  const words = categories.flatMap(c => WORD_CATEGORIES[c] || []);
  return words.some(w => checkBonusRule(bonus, w));
}
